/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as __tests___institutionTestHelpers from "../__tests__/institutionTestHelpers.js";
import type * as _botRubricFixture from "../_botRubricFixture.js";
import type * as academicCalendar from "../academicCalendar.js";
import type * as acceleration from "../acceleration.js";
import type * as accessGuards from "../accessGuards.js";
import type * as accessPreview from "../accessPreview.js";
import type * as accountPassword from "../accountPassword.js";
import type * as activities from "../activities.js";
import type * as activityCompletions from "../activityCompletions.js";
import type * as activityResourceActions from "../activityResourceActions.js";
import type * as activityResources from "../activityResources.js";
import type * as activitySessions from "../activitySessions.js";
import type * as adminCloneScholar from "../adminCloneScholar.js";
import type * as adminMigrateDossierTeacherBlocks from "../adminMigrateDossierTeacherBlocks.js";
import type * as adminTermTools from "../adminTermTools.js";
import type * as alerts from "../alerts.js";
import type * as analysisHelpers from "../analysisHelpers.js";
import type * as appAudiences from "../appAudiences.js";
import type * as appStates from "../appStates.js";
import type * as artifacts from "../artifacts.js";
import type * as assessmentBinder from "../assessmentBinder.js";
import type * as assets_fonts_hankenGroteskBold from "../assets/fonts/hankenGroteskBold.js";
import type * as assets_fonts_hankenGroteskItalic from "../assets/fonts/hankenGroteskItalic.js";
import type * as assets_fonts_hankenGroteskRegular from "../assets/fonts/hankenGroteskRegular.js";
import type * as assets_fonts_hankenGroteskSemiBold from "../assets/fonts/hankenGroteskSemiBold.js";
import type * as assets_fonts_index from "../assets/fonts/index.js";
import type * as assets_fonts_playfairDisplayRegular from "../assets/fonts/playfairDisplayRegular.js";
import type * as assets_seal_index from "../assets/seal/index.js";
import type * as assets_seal_primaryInstitutionSeal from "../assets/seal/primaryInstitutionSeal.js";
import type * as assignments from "../assignments.js";
import type * as audioActions from "../audioActions.js";
import type * as auth from "../auth.js";
import type * as badgeArtActions from "../badgeArtActions.js";
import type * as badges from "../badges.js";
import type * as bakeEval from "../bakeEval.js";
import type * as bakePaths from "../bakePaths.js";
import type * as bakeUnitFromSeed from "../bakeUnitFromSeed.js";
import type * as birthdays from "../birthdays.js";
import type * as bugReports from "../bugReports.js";
import type * as calculatorLicenses from "../calculatorLicenses.js";
import type * as captureStations from "../captureStations.js";
import type * as changelog from "../changelog.js";
import type * as chatInstruction from "../chatInstruction.js";
import type * as chatPractice from "../chatPractice.js";
import type * as chatTitles from "../chatTitles.js";
import type * as classDigestActions from "../classDigestActions.js";
import type * as classDigests from "../classDigests.js";
import type * as classResolver from "../classResolver.js";
import type * as closureLines from "../closureLines.js";
import type * as cohortPractice from "../cohortPractice.js";
import type * as conceptAtlas from "../conceptAtlas.js";
import type * as concepts from "../concepts.js";
import type * as courseNarratives from "../courseNarratives.js";
import type * as crons from "../crons.js";
import type * as crossDomainConnections from "../crossDomainConnections.js";
import type * as curriculumAssistant from "../curriculumAssistant.js";
import type * as curriculumExperiments from "../curriculumExperiments.js";
import type * as curriculumSim from "../curriculumSim.js";
import type * as customApps from "../customApps.js";
import type * as dailyRecap from "../dailyRecap.js";
import type * as debugBotCheck from "../debugBotCheck.js";
import type * as deliverableAssess from "../deliverableAssess.js";
import type * as deliverables from "../deliverables.js";
import type * as devPilot from "../devPilot.js";
import type * as devPurge from "../devPurge.js";
import type * as devTools from "../devTools.js";
import type * as deviceAppUnlock from "../deviceAppUnlock.js";
import type * as deviceLock from "../deviceLock.js";
import type * as devicePairing from "../devicePairing.js";
import type * as deviceSignOut from "../deviceSignOut.js";
import type * as dossier from "../dossier.js";
import type * as driveSync from "../driveSync.js";
import type * as driveSyncState from "../driveSyncState.js";
import type * as edgeStories from "../edgeStories.js";
import type * as embedAuth from "../embedAuth.js";
import type * as enrollment from "../enrollment.js";
import type * as enrollmentImport from "../enrollmentImport.js";
import type * as eodCheckin from "../eodCheckin.js";
import type * as eodCheckinNarrative from "../eodCheckinNarrative.js";
import type * as equipment from "../equipment.js";
import type * as equipmentActions from "../equipmentActions.js";
import type * as evalExport from "../evalExport.js";
import type * as externalApps from "../externalApps.js";
import type * as feedMetrics from "../feedMetrics.js";
import type * as files from "../files.js";
import type * as flairArt from "../flairArt.js";
import type * as flairArtActions from "../flairArtActions.js";
import type * as flairArtInternal from "../flairArtInternal.js";
import type * as gameObserver from "../gameObserver.js";
import type * as games from "../games.js";
import type * as googleAccounts from "../googleAccounts.js";
import type * as googleAccountsActions from "../googleAccountsActions.js";
import type * as googleDocsEvents from "../googleDocsEvents.js";
import type * as googleDocsEventsActions from "../googleDocsEventsActions.js";
import type * as granuleAssessment from "../granuleAssessment.js";
import type * as granuleEvidence from "../granuleEvidence.js";
import type * as graphemeActions from "../graphemeActions.js";
import type * as graphemeInventory from "../graphemeInventory.js";
import type * as handoffTranscripts from "../handoffTranscripts.js";
import type * as historicalThinkingData from "../historicalThinkingData.js";
import type * as http from "../http.js";
import type * as impersonation from "../impersonation.js";
import type * as improvementTraces from "../improvementTraces.js";
import type * as institutionDeletion from "../institutionDeletion.js";
import type * as institutionInvites from "../institutionInvites.js";
import type * as institutionLifecycle from "../institutionLifecycle.js";
import type * as institutions from "../institutions.js";
import type * as instruction from "../instruction.js";
import type * as instructionVideoHealth from "../instructionVideoHealth.js";
import type * as interpretive from "../interpretive.js";
import type * as interpretiveHelpers from "../interpretiveHelpers.js";
import type * as judgeValidation from "../judgeValidation.js";
import type * as keyMoments from "../keyMoments.js";
import type * as knowledgeNodes from "../knowledgeNodes.js";
import type * as knowledgeState from "../knowledgeState.js";
import type * as knowledgeTree from "../knowledgeTree.js";
import type * as learningRecord from "../learningRecord.js";
import type * as lessons from "../lessons.js";
import type * as lib_access from "../lib/access.js";
import type * as lib_activityCascade from "../lib/activityCascade.js";
import type * as lib_activityCompletionCore from "../lib/activityCompletionCore.js";
import type * as lib_activityCompletionEligibility from "../lib/activityCompletionEligibility.js";
import type * as lib_activityCompletionTool from "../lib/activityCompletionTool.js";
import type * as lib_activityKindTools from "../lib/activityKindTools.js";
import type * as lib_activityPresentationResources from "../lib/activityPresentationResources.js";
import type * as lib_activityResourceDisplay from "../lib/activityResourceDisplay.js";
import type * as lib_activityResourceReachability from "../lib/activityResourceReachability.js";
import type * as lib_activitySessions from "../lib/activitySessions.js";
import type * as lib_aideAttachments from "../lib/aideAttachments.js";
import type * as lib_aideFocus from "../lib/aideFocus.js";
import type * as lib_aideModel from "../lib/aideModel.js";
import type * as lib_aideResolvers from "../lib/aideResolvers.js";
import type * as lib_aideStream from "../lib/aideStream.js";
import type * as lib_aideTools from "../lib/aideTools.js";
import type * as lib_aideUploadMimes from "../lib/aideUploadMimes.js";
import type * as lib_anthropic from "../lib/anthropic.js";
import type * as lib_appAudiences from "../lib/appAudiences.js";
import type * as lib_asnStandardsAdapter from "../lib/asnStandardsAdapter.js";
import type * as lib_assessmentBinder from "../lib/assessmentBinder.js";
import type * as lib_assignmentTools from "../lib/assignmentTools.js";
import type * as lib_atlasEdges from "../lib/atlasEdges.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_authConstants from "../lib/authConstants.js";
import type * as lib_authGuards from "../lib/authGuards.js";
import type * as lib_badgeArt from "../lib/badgeArt.js";
import type * as lib_badgeAward from "../lib/badgeAward.js";
import type * as lib_badgeChroma from "../lib/badgeChroma.js";
import type * as lib_bloomRigor from "../lib/bloomRigor.js";
import type * as lib_botTools from "../lib/botTools.js";
import type * as lib_canvasHtml from "../lib/canvasHtml.js";
import type * as lib_cascade from "../lib/cascade.js";
import type * as lib_channels from "../lib/channels.js";
import type * as lib_chromaImage from "../lib/chromaImage.js";
import type * as lib_claimInviteEmail from "../lib/claimInviteEmail.js";
import type * as lib_classResolver from "../lib/classResolver.js";
import type * as lib_claudeFileExtraction from "../lib/claudeFileExtraction.js";
import type * as lib_closureLinePrompt from "../lib/closureLinePrompt.js";
import type * as lib_conceptLabels from "../lib/conceptLabels.js";
import type * as lib_curatedExplorationCatalog from "../lib/curatedExplorationCatalog.js";
import type * as lib_curriculumAccess from "../lib/curriculumAccess.js";
import type * as lib_curriculumDiff from "../lib/curriculumDiff.js";
import type * as lib_curriculumDimensions from "../lib/curriculumDimensions.js";
import type * as lib_curriculumDuplication from "../lib/curriculumDuplication.js";
import type * as lib_curriculumGround from "../lib/curriculumGround.js";
import type * as lib_curriculumImprover from "../lib/curriculumImprover.js";
import type * as lib_curriculumJudge from "../lib/curriculumJudge.js";
import type * as lib_curriculumOptimize from "../lib/curriculumOptimize.js";
import type * as lib_curriculumPreflightResult from "../lib/curriculumPreflightResult.js";
import type * as lib_curriculumProbe from "../lib/curriculumProbe.js";
import type * as lib_curriculumScore from "../lib/curriculumScore.js";
import type * as lib_curriculumSimShared from "../lib/curriculumSimShared.js";
import type * as lib_customAppTools from "../lib/customAppTools.js";
import type * as lib_customFunctions from "../lib/customFunctions.js";
import type * as lib_dailyRecap from "../lib/dailyRecap.js";
import type * as lib_deliverable from "../lib/deliverable.js";
import type * as lib_deploymentConfig from "../lib/deploymentConfig.js";
import type * as lib_deploymentSafety from "../lib/deploymentSafety.js";
import type * as lib_deviceAppProjection from "../lib/deviceAppProjection.js";
import type * as lib_deviceAppUnlockScheduling from "../lib/deviceAppUnlockScheduling.js";
import type * as lib_digestStaleness from "../lib/digestStaleness.js";
import type * as lib_documentKinds from "../lib/documentKinds.js";
import type * as lib_domainTaxonomy from "../lib/domainTaxonomy.js";
import type * as lib_driveAccess from "../lib/driveAccess.js";
import type * as lib_email from "../lib/email.js";
import type * as lib_enrollmentStanding from "../lib/enrollmentStanding.js";
import type * as lib_eodCheckin from "../lib/eodCheckin.js";
import type * as lib_equipmentIdentify from "../lib/equipmentIdentify.js";
import type * as lib_equipmentPhotoBlob from "../lib/equipmentPhotoBlob.js";
import type * as lib_exactTextMatch from "../lib/exactTextMatch.js";
import type * as lib_externalAppIconUrl from "../lib/externalAppIconUrl.js";
import type * as lib_externalAppReach from "../lib/externalAppReach.js";
import type * as lib_externalAppsResolve from "../lib/externalAppsResolve.js";
import type * as lib_externalAppsSeed from "../lib/externalAppsSeed.js";
import type * as lib_externalAppsTools from "../lib/externalAppsTools.js";
import type * as lib_feedMomentum from "../lib/feedMomentum.js";
import type * as lib_fileTextExtraction from "../lib/fileTextExtraction.js";
import type * as lib_fleetHardwareContext from "../lib/fleetHardwareContext.js";
import type * as lib_formInstitutionGate from "../lib/formInstitutionGate.js";
import type * as lib_formRegistry from "../lib/formRegistry.js";
import type * as lib_formReminderEmail from "../lib/formReminderEmail.js";
import type * as lib_gemini from "../lib/gemini.js";
import type * as lib_geomapAssetsTool from "../lib/geomapAssetsTool.js";
import type * as lib_githubSignature from "../lib/githubSignature.js";
import type * as lib_google from "../lib/google.js";
import type * as lib_googleDocsApi from "../lib/googleDocsApi.js";
import type * as lib_googleDocsCommentReply from "../lib/googleDocsCommentReply.js";
import type * as lib_googleDocsCommentTools from "../lib/googleDocsCommentTools.js";
import type * as lib_googleDocsEditor from "../lib/googleDocsEditor.js";
import type * as lib_googleDocsEventsConstants from "../lib/googleDocsEventsConstants.js";
import type * as lib_googleDocsText from "../lib/googleDocsText.js";
import type * as lib_googleDocsTools from "../lib/googleDocsTools.js";
import type * as lib_googleEventsPush from "../lib/googleEventsPush.js";
import type * as lib_googleSlidesApi from "../lib/googleSlidesApi.js";
import type * as lib_googleSlidesEditor from "../lib/googleSlidesEditor.js";
import type * as lib_googleTokens from "../lib/googleTokens.js";
import type * as lib_granules from "../lib/granules.js";
import type * as lib_graphemeAnnotate from "../lib/graphemeAnnotate.js";
import type * as lib_growthStories from "../lib/growthStories.js";
import type * as lib_guardianFormTools from "../lib/guardianFormTools.js";
import type * as lib_healthRecord from "../lib/healthRecord.js";
import type * as lib_healthRecordConfirmationEmail from "../lib/healthRecordConfirmationEmail.js";
import type * as lib_healthRecordTools from "../lib/healthRecordTools.js";
import type * as lib_imageBytes from "../lib/imageBytes.js";
import type * as lib_imageSearch from "../lib/imageSearch.js";
import type * as lib_impersonationConfig from "../lib/impersonationConfig.js";
import type * as lib_independentStudy from "../lib/independentStudy.js";
import type * as lib_inflateRaw from "../lib/inflateRaw.js";
import type * as lib_ingestMimes from "../lib/ingestMimes.js";
import type * as lib_inputModality from "../lib/inputModality.js";
import type * as lib_institutionInvites from "../lib/institutionInvites.js";
import type * as lib_institutionLens from "../lib/institutionLens.js";
import type * as lib_institutionPromptProfile from "../lib/institutionPromptProfile.js";
import type * as lib_institutionTime from "../lib/institutionTime.js";
import type * as lib_judgeCorrelation from "../lib/judgeCorrelation.js";
import type * as lib_knowledgeNodeEdges from "../lib/knowledgeNodeEdges.js";
import type * as lib_knowledgeNodeResolver from "../lib/knowledgeNodeResolver.js";
import type * as lib_knowledgeTreeData from "../lib/knowledgeTreeData.js";
import type * as lib_knowledgeTreeFrontier from "../lib/knowledgeTreeFrontier.js";
import type * as lib_labelAgreement from "../lib/labelAgreement.js";
import type * as lib_leapSeeds from "../lib/leapSeeds.js";
import type * as lib_magicAnnotations from "../lib/magicAnnotations.js";
import type * as lib_magicLinkEmail from "../lib/magicLinkEmail.js";
import type * as lib_managedDeviceClaimState from "../lib/managedDeviceClaimState.js";
import type * as lib_managedNativeApps from "../lib/managedNativeApps.js";
import type * as lib_masterScheduleTools from "../lib/masterScheduleTools.js";
import type * as lib_messageLinkPreview from "../lib/messageLinkPreview.js";
import type * as lib_metaBlocks from "../lib/metaBlocks.js";
import type * as lib_models from "../lib/models.js";
import type * as lib_momentInterestingness from "../lib/momentInterestingness.js";
import type * as lib_moments_storyMomentPolicy from "../lib/moments/storyMomentPolicy.js";
import type * as lib_nodeDepthHelpers from "../lib/nodeDepthHelpers.js";
import type * as lib_oauthCrypto from "../lib/oauthCrypto.js";
import type * as lib_observerShared from "../lib/observerShared.js";
import type * as lib_parentAidePrompt from "../lib/parentAidePrompt.js";
import type * as lib_parentMessageChannels from "../lib/parentMessageChannels.js";
import type * as lib_parentMessageEmail from "../lib/parentMessageEmail.js";
import type * as lib_passkeyConfig from "../lib/passkeyConfig.js";
import type * as lib_passwordCrypto from "../lib/passwordCrypto.js";
import type * as lib_pca from "../lib/pca.js";
import type * as lib_pcm from "../lib/pcm.js";
import type * as lib_pdfSegments from "../lib/pdfSegments.js";
import type * as lib_pdfSubstitute from "../lib/pdfSubstitute.js";
import type * as lib_physicalEnvTools from "../lib/physicalEnvTools.js";
import type * as lib_portfolioAttributions from "../lib/portfolioAttributions.js";
import type * as lib_portfolioStatus from "../lib/portfolioStatus.js";
import type * as lib_practice_answerShape from "../lib/practice/answerShape.js";
import type * as lib_practice_answers from "../lib/practice/answers.js";
import type * as lib_practice_applicationEligibility from "../lib/practice/applicationEligibility.js";
import type * as lib_practice_calibration from "../lib/practice/calibration.js";
import type * as lib_practice_chatInstruction from "../lib/practice/chatInstruction.js";
import type * as lib_practice_chatPractice from "../lib/practice/chatPractice.js";
import type * as lib_practice_checkpointFocus from "../lib/practice/checkpointFocus.js";
import type * as lib_practice_countableReconstruct from "../lib/practice/countableReconstruct.js";
import type * as lib_practice_coverage from "../lib/practice/coverage.js";
import type * as lib_practice_crossDomainSeeds from "../lib/practice/crossDomainSeeds.js";
import type * as lib_practice_dialogueStretch from "../lib/practice/dialogueStretch.js";
import type * as lib_practice_dispatchCompletion from "../lib/practice/dispatchCompletion.js";
import type * as lib_practice_domainMapStatus from "../lib/practice/domainMapStatus.js";
import type * as lib_practice_domainRetention from "../lib/practice/domainRetention.js";
import type * as lib_practice_domains from "../lib/practice/domains.js";
import type * as lib_practice_errorFlags from "../lib/practice/errorFlags.js";
import type * as lib_practice_errorPatterns from "../lib/practice/errorPatterns.js";
import type * as lib_practice_evalExpr from "../lib/practice/evalExpr.js";
import type * as lib_practice_factFluency from "../lib/practice/factFluency.js";
import type * as lib_practice_factSprint from "../lib/practice/factSprint.js";
import type * as lib_practice_fadedSteps from "../lib/practice/fadedSteps.js";
import type * as lib_practice_fastMath from "../lib/practice/fastMath.js";
import type * as lib_practice_fastMathRead from "../lib/practice/fastMathRead.js";
import type * as lib_practice_frontierGrade from "../lib/practice/frontierGrade.js";
import type * as lib_practice_gameBeats from "../lib/practice/gameBeats.js";
import type * as lib_practice_gateEval from "../lib/practice/gateEval.js";
import type * as lib_practice_graphValidation from "../lib/practice/graphValidation.js";
import type * as lib_practice_handoff from "../lib/practice/handoff.js";
import type * as lib_practice_implicitCredit from "../lib/practice/implicitCredit.js";
import type * as lib_practice_instructionEntries from "../lib/practice/instructionEntries.js";
import type * as lib_practice_instructionVerify from "../lib/practice/instructionVerify.js";
import type * as lib_practice_latencyStats from "../lib/practice/latencyStats.js";
import type * as lib_practice_manipulativeKindUsage from "../lib/practice/manipulativeKindUsage.js";
import type * as lib_practice_mapping from "../lib/practice/mapping.js";
import type * as lib_practice_mathPlan from "../lib/practice/mathPlan.js";
import type * as lib_practice_mathSkillsNarrative from "../lib/practice/mathSkillsNarrative.js";
import type * as lib_practice_mixedQueue from "../lib/practice/mixedQueue.js";
import type * as lib_practice_padHints from "../lib/practice/padHints.js";
import type * as lib_practice_paramHealth from "../lib/practice/paramHealth.js";
import type * as lib_practice_placement from "../lib/practice/placement.js";
import type * as lib_practice_plainText from "../lib/practice/plainText.js";
import type * as lib_practice_promptVisual from "../lib/practice/promptVisual.js";
import type * as lib_practice_remediation from "../lib/practice/remediation.js";
import type * as lib_practice_revealLine from "../lib/practice/revealLine.js";
import type * as lib_practice_reveals from "../lib/practice/reveals.js";
import type * as lib_practice_scheduler from "../lib/practice/scheduler.js";
import type * as lib_practice_scholarLatencyBaseline from "../lib/practice/scholarLatencyBaseline.js";
import type * as lib_practice_seedSpawn from "../lib/practice/seedSpawn.js";
import type * as lib_practice_segments from "../lib/practice/segments.js";
import type * as lib_practice_servable from "../lib/practice/servable.js";
import type * as lib_practice_serve from "../lib/practice/serve.js";
import type * as lib_practice_session from "../lib/practice/session.js";
import type * as lib_practice_spiralBreaker from "../lib/practice/spiralBreaker.js";
import type * as lib_practice_storyDigest from "../lib/practice/storyDigest.js";
import type * as lib_practice_storyOpen from "../lib/practice/storyOpen.js";
import type * as lib_practice_storyRegistry from "../lib/practice/storyRegistry.js";
import type * as lib_practice_stuckAlertBody from "../lib/practice/stuckAlertBody.js";
import type * as lib_practice_stuckAlertPrompt from "../lib/practice/stuckAlertPrompt.js";
import type * as lib_practice_summits from "../lib/practice/summits.js";
import type * as lib_practice_templates from "../lib/practice/templates.js";
import type * as lib_practice_tuneup from "../lib/practice/tuneup.js";
import type * as lib_practice_verify from "../lib/practice/verify.js";
import type * as lib_practice_weeklyMathTopics from "../lib/practice/weeklyMathTopics.js";
import type * as lib_practice_workedStepGen from "../lib/practice/workedStepGen.js";
import type * as lib_practiceAtlasLayout from "../lib/practiceAtlasLayout.js";
import type * as lib_practiceDigest from "../lib/practiceDigest.js";
import type * as lib_practicePoolTools from "../lib/practicePoolTools.js";
import type * as lib_practiceSkillTreeTools from "../lib/practiceSkillTreeTools.js";
import type * as lib_prepBlock from "../lib/prepBlock.js";
import type * as lib_primaryInstitution from "../lib/primaryInstitution.js";
import type * as lib_primaryInstitutionPrintIdentity from "../lib/primaryInstitutionPrintIdentity.js";
import type * as lib_primaryInstitutionPromptProfile from "../lib/primaryInstitutionPromptProfile.js";
import type * as lib_printRelayHttp from "../lib/printRelayHttp.js";
import type * as lib_profileImage from "../lib/profileImage.js";
import type * as lib_programGroupAccess from "../lib/programGroupAccess.js";
import type * as lib_programGuestWork from "../lib/programGuestWork.js";
import type * as lib_programHandoutAccess from "../lib/programHandoutAccess.js";
import type * as lib_promptVersion from "../lib/promptVersion.js";
import type * as lib_pushes from "../lib/pushes.js";
import type * as lib_questLifecycle from "../lib/questLifecycle.js";
import type * as lib_readingLevels from "../lib/readingLevels.js";
import type * as lib_rehearsalBudget from "../lib/rehearsalBudget.js";
import type * as lib_resendInbound from "../lib/resendInbound.js";
import type * as lib_roles from "../lib/roles.js";
import type * as lib_rooms from "../lib/rooms.js";
import type * as lib_rosterPulse from "../lib/rosterPulse.js";
import type * as lib_rubricScoreTool from "../lib/rubricScoreTool.js";
import type * as lib_sandbox from "../lib/sandbox.js";
import type * as lib_scheduleMirror from "../lib/scheduleMirror.js";
import type * as lib_schedulePlacementIdentity from "../lib/schedulePlacementIdentity.js";
import type * as lib_scholarCodeTools from "../lib/scholarCodeTools.js";
import type * as lib_scholarCredential from "../lib/scholarCredential.js";
import type * as lib_scholarEnrollment from "../lib/scholarEnrollment.js";
import type * as lib_scholarGroupMembership from "../lib/scholarGroupMembership.js";
import type * as lib_scholarGroupUnlocks from "../lib/scholarGroupUnlocks.js";
import type * as lib_scholarIdeaTools from "../lib/scholarIdeaTools.js";
import type * as lib_scholarMatch from "../lib/scholarMatch.js";
import type * as lib_scholarParticipationTooling from "../lib/scholarParticipationTooling.js";
import type * as lib_scholarPronouns from "../lib/scholarPronouns.js";
import type * as lib_scholarReadPolicy from "../lib/scholarReadPolicy.js";
import type * as lib_scholarReadTools from "../lib/scholarReadTools.js";
import type * as lib_scholarReads from "../lib/scholarReads.js";
import type * as lib_scholarSafeText from "../lib/scholarSafeText.js";
import type * as lib_scholarWriteTools from "../lib/scholarWriteTools.js";
import type * as lib_schoolDay from "../lib/schoolDay.js";
import type * as lib_schoolDays from "../lib/schoolDays.js";
import type * as lib_schoolMediaConsent from "../lib/schoolMediaConsent.js";
import type * as lib_seedLabel from "../lib/seedLabel.js";
import type * as lib_seeds from "../lib/seeds.js";
import type * as lib_selSynthesisPrompt from "../lib/selSynthesisPrompt.js";
import type * as lib_serviceAccount from "../lib/serviceAccount.js";
import type * as lib_sessionActivitySetup from "../lib/sessionActivitySetup.js";
import type * as lib_sessionRecap from "../lib/sessionRecap.js";
import type * as lib_simulatorRedTeam from "../lib/simulatorRedTeam.js";
import type * as lib_simulatorRunBudget from "../lib/simulatorRunBudget.js";
import type * as lib_simulatorRunEvidence from "../lib/simulatorRunEvidence.js";
import type * as lib_simulatorTemplatesCatalog from "../lib/simulatorTemplatesCatalog.js";
import type * as lib_skyField from "../lib/skyField.js";
import type * as lib_skyMuseum from "../lib/skyMuseum.js";
import type * as lib_skySeedSelection from "../lib/skySeedSelection.js";
import type * as lib_slackApi from "../lib/slackApi.js";
import type * as lib_slackCanvasReport from "../lib/slackCanvasReport.js";
import type * as lib_slackLists from "../lib/slackLists.js";
import type * as lib_slackPermalink from "../lib/slackPermalink.js";
import type * as lib_slackSignature from "../lib/slackSignature.js";
import type * as lib_slackText from "../lib/slackText.js";
import type * as lib_slackTools from "../lib/slackTools.js";
import type * as lib_slackTranscript from "../lib/slackTranscript.js";
import type * as lib_slideImageFidelity from "../lib/slideImageFidelity.js";
import type * as lib_slidesMedia from "../lib/slidesMedia.js";
import type * as lib_slidesRender from "../lib/slidesRender.js";
import type * as lib_specialDeliveryEditorial from "../lib/specialDeliveryEditorial.js";
import type * as lib_specialDeliveryInsertShared from "../lib/specialDeliveryInsertShared.js";
import type * as lib_specialDeliveryPrint from "../lib/specialDeliveryPrint.js";
import type * as lib_specialDeliverySketchImage from "../lib/specialDeliverySketchImage.js";
import type * as lib_staffCapabilities from "../lib/staffCapabilities.js";
import type * as lib_standardNotation from "../lib/standardNotation.js";
import type * as lib_standardStrand from "../lib/standardStrand.js";
import type * as lib_suggestionTools from "../lib/suggestionTools.js";
import type * as lib_teachBack from "../lib/teachBack.js";
import type * as lib_testDriveReplay from "../lib/testDriveReplay.js";
import type * as lib_textToTitle from "../lib/textToTitle.js";
import type * as lib_themeIconArt from "../lib/themeIconArt.js";
import type * as lib_thumbnail from "../lib/thumbnail.js";
import type * as lib_toolActivityGroups from "../lib/toolActivityGroups.js";
import type * as lib_toolLabels from "../lib/toolLabels.js";
import type * as lib_tutorClosingGuidance from "../lib/tutorClosingGuidance.js";
import type * as lib_tutorSessionTools from "../lib/tutorSessionTools.js";
import type * as lib_unitAccess from "../lib/unitAccess.js";
import type * as lib_unitDesignSerializer from "../lib/unitDesignSerializer.js";
import type * as lib_unitDesignerTools from "../lib/unitDesignerTools.js";
import type * as lib_unitMaturity from "../lib/unitMaturity.js";
import type * as lib_usage from "../lib/usage.js";
import type * as lib_usageReport from "../lib/usageReport.js";
import type * as lib_username from "../lib/username.js";
import type * as lib_webActivityTarget from "../lib/webActivityTarget.js";
import type * as lib_webSessionSummary from "../lib/webSessionSummary.js";
import type * as libraryCards from "../libraryCards.js";
import type * as llmBudget from "../llmBudget.js";
import type * as magicAnnotations from "../magicAnnotations.js";
import type * as managedDeviceClaims from "../managedDeviceClaims.js";
import type * as manipulativeThemeIconActions from "../manipulativeThemeIconActions.js";
import type * as manipulativeThemeIcons from "../manipulativeThemeIcons.js";
import type * as mapGates from "../mapGates.js";
import type * as masterSchedule from "../masterSchedule.js";
import type * as masteryObservations from "../masteryObservations.js";
import type * as masteryReDerive from "../masteryReDerive.js";
import type * as mathFocus from "../mathFocus.js";
import type * as mathPlans from "../mathPlans.js";
import type * as mathPortrait from "../mathPortrait.js";
import type * as mcp from "../mcp.js";
import type * as mcpOauth from "../mcpOauth.js";
import type * as memberships from "../memberships.js";
import type * as messageFlags from "../messageFlags.js";
import type * as messageLinkPreviewCache from "../messageLinkPreviewCache.js";
import type * as messageLinkPreviews from "../messageLinkPreviews.js";
import type * as messages from "../messages.js";
import type * as metaChat from "../metaChat.js";
import type * as metaObserver from "../metaObserver.js";
import type * as metaPrompts from "../metaPrompts.js";
import type * as nativeClientHeartbeat from "../nativeClientHeartbeat.js";
import type * as ngssData from "../ngssData.js";
import type * as nodeDepth from "../nodeDepth.js";
import type * as nodeNeighbourhood from "../nodeNeighbourhood.js";
import type * as notifications from "../notifications.js";
import type * as observations from "../observations.js";
import type * as observer from "../observer.js";
import type * as onboarding from "../onboarding.js";
import type * as onboardingData from "../onboardingData.js";
import type * as openMap from "../openMap.js";
import type * as parentChat from "../parentChat.js";
import type * as parentMessageSend from "../parentMessageSend.js";
import type * as parentMessageSlack from "../parentMessageSlack.js";
import type * as parentMessages from "../parentMessages.js";
import type * as parents from "../parents.js";
import type * as passkeys from "../passkeys.js";
import type * as personas from "../personas.js";
import type * as perspectives from "../perspectives.js";
import type * as physicalEnvAide from "../physicalEnvAide.js";
import type * as physicalTasks from "../physicalTasks.js";
import type * as portfolio from "../portfolio.js";
import type * as portfolioActions from "../portfolioActions.js";
import type * as portfolioAssess from "../portfolioAssess.js";
import type * as portfolioIngestions from "../portfolioIngestions.js";
import type * as portfolioMaterialize from "../portfolioMaterialize.js";
import type * as portfolioRefile from "../portfolioRefile.js";
import type * as portfolioRefileMutations from "../portfolioRefileMutations.js";
import type * as portfolioRepair from "../portfolioRepair.js";
import type * as portfolioThumbs from "../portfolioThumbs.js";
import type * as practiceAtlas from "../practiceAtlas.js";
import type * as practiceAtlasData from "../practiceAtlasData.js";
import type * as practiceCalibration from "../practiceCalibration.js";
import type * as practiceDialogue from "../practiceDialogue.js";
import type * as practiceDigest from "../practiceDigest.js";
import type * as practiceGames from "../practiceGames.js";
import type * as practiceGen from "../practiceGen.js";
import type * as practiceHintActions from "../practiceHintActions.js";
import type * as practiceInstruments from "../practiceInstruments.js";
import type * as practiceItemPool from "../practiceItemPool.js";
import type * as practiceMoments from "../practiceMoments.js";
import type * as practicePadHints from "../practicePadHints.js";
import type * as practiceSkills from "../practiceSkills.js";
import type * as practiceStuckAlert from "../practiceStuckAlert.js";
import type * as practiceTextCleanup from "../practiceTextCleanup.js";
import type * as practiceTuneups from "../practiceTuneups.js";
import type * as practiceWorkImages from "../practiceWorkImages.js";
import type * as processState from "../processState.js";
import type * as processes from "../processes.js";
import type * as prompts from "../prompts.js";
import type * as pushes from "../pushes.js";
import type * as qualityLabeling from "../qualityLabeling.js";
import type * as quests from "../quests.js";
import type * as readingLevelAnalysis from "../readingLevelAnalysis.js";
import type * as realtimeTranscription from "../realtimeTranscription.js";
import type * as reportingPeriods from "../reportingPeriods.js";
import type * as roomCues from "../roomCues.js";
import type * as rooms from "../rooms.js";
import type * as rounds from "../rounds.js";
import type * as sandboxActions from "../sandboxActions.js";
import type * as scholarActivityAngles from "../scholarActivityAngles.js";
import type * as scholarApps from "../scholarApps.js";
import type * as scholarDocumentActions from "../scholarDocumentActions.js";
import type * as scholarDocumentProposalActions from "../scholarDocumentProposalActions.js";
import type * as scholarDocumentProposals from "../scholarDocumentProposals.js";
import type * as scholarDocuments from "../scholarDocuments.js";
import type * as scholarGoals from "../scholarGoals.js";
import type * as scholarGroups from "../scholarGroups.js";
import type * as scholarHealthRecords from "../scholarHealthRecords.js";
import type * as scholarPlate from "../scholarPlate.js";
import type * as scholarSuggestions from "../scholarSuggestions.js";
import type * as scholarUnitBadges from "../scholarUnitBadges.js";
import type * as scholars from "../scholars.js";
import type * as seed_algebra1Graph from "../seed/algebra1Graph.js";
import type * as seed_assessmentDemo from "../seed/assessmentDemo.js";
import type * as seed_cooperationConflict from "../seed/cooperationConflict.js";
import type * as seed_devPersonas from "../seed/devPersonas.js";
import type * as seed_discreteMathGraph from "../seed/discreteMathGraph.js";
import type * as seed_earlyAlgebraGraph from "../seed/earlyAlgebraGraph.js";
import type * as seed_fractionArithmeticGraph from "../seed/fractionArithmeticGraph.js";
import type * as seed_gamesDemo from "../seed/gamesDemo.js";
import type * as seed_geographyQuests from "../seed/geographyQuests.js";
import type * as seed_geometryMeasurementGraph from "../seed/geometryMeasurementGraph.js";
import type * as seed_institutions from "../seed/institutions.js";
import type * as seed_instructionSeed from "../seed/instructionSeed.js";
import type * as seed_integersCoordinatesGraph from "../seed/integersCoordinatesGraph.js";
import type * as seed_launchpadDemo from "../seed/launchpadDemo.js";
import type * as seed_physicalEnvironment from "../seed/physicalEnvironment.js";
import type * as seed_probabilityGraph from "../seed/probabilityGraph.js";
import type * as seed_prodBlockSchedule from "../seed/prodBlockSchedule.js";
import type * as seed_programFamilies from "../seed/programFamilies.js";
import type * as seed_ratioProportionPercentGraph from "../seed/ratioProportionPercentGraph.js";
import type * as seed_rich_badgeArtAssets from "../seed/rich/badgeArtAssets.js";
import type * as seed_rich_chat from "../seed/rich/chat.js";
import type * as seed_rich_curriculum from "../seed/rich/curriculum.js";
import type * as seed_rich_execution from "../seed/rich/execution.js";
import type * as seed_rich_index from "../seed/rich/index.js";
import type * as seed_rich_observation from "../seed/rich/observation.js";
import type * as seed_rich_practice from "../seed/rich/practice.js";
import type * as seed_rich_robotics from "../seed/rich/robotics.js";
import type * as seed_rich_roster from "../seed/rich/roster.js";
import type * as seed_rich_schedule from "../seed/rich/schedule.js";
import type * as seed_rich_sims from "../seed/rich/sims.js";
import type * as seed_rich_types from "../seed/rich/types.js";
import type * as seed_rosterPulseDemo from "../seed/rosterPulseDemo.js";
import type * as seed_sampleReports from "../seed/sampleReports.js";
import type * as seed_storyArtAssets from "../seed/storyArtAssets.js";
import type * as seed_stretchItems from "../seed/stretchItems.js";
import type * as seed_systemsAgents from "../seed/systemsAgents.js";
import type * as seed_wholeNumberArithmeticGraph from "../seed/wholeNumberArithmeticGraph.js";
import type * as seedAiLiteracyUnits from "../seedAiLiteracyUnits.js";
import type * as seedAtlasDemo from "../seedAtlasDemo.js";
import type * as seedAutoRubricForTesting from "../seedAutoRubricForTesting.js";
import type * as seedBadgeArt from "../seedBadgeArt.js";
import type * as seedData from "../seedData.js";
import type * as seedDigestDemo from "../seedDigestDemo.js";
import type * as seedMasterSchedule from "../seedMasterSchedule.js";
import type * as seedMisconceptionForTesting from "../seedMisconceptionForTesting.js";
import type * as seedProbabilityStrand from "../seedProbabilityStrand.js";
import type * as seedProdUnits from "../seedProdUnits.js";
import type * as seedProdUnitsData from "../seedProdUnitsData.js";
import type * as seedRichCohort from "../seedRichCohort.js";
import type * as seedRoboticsMedia from "../seedRoboticsMedia.js";
import type * as seedRubricActivityForTesting from "../seedRubricActivityForTesting.js";
import type * as seedTranscribeDemoForTesting from "../seedTranscribeDemoForTesting.js";
import type * as seedUnitForTesting from "../seedUnitForTesting.js";
import type * as seeds from "../seeds.js";
import type * as selSyntheses from "../selSyntheses.js";
import type * as selSynthesisActions from "../selSynthesisActions.js";
import type * as selSynthesisCron from "../selSynthesisCron.js";
import type * as sessionContextHelpers from "../sessionContextHelpers.js";
import type * as sessionHelpers from "../sessionHelpers.js";
import type * as sessionSignals from "../sessionSignals.js";
import type * as sessionStreamHelpers from "../sessionStreamHelpers.js";
import type * as sessionTitles from "../sessionTitles.js";
import type * as sessions from "../sessions.js";
import type * as shareBack from "../shareBack.js";
import type * as shareBackActions from "../shareBackActions.js";
import type * as simplemdm from "../simplemdm.js";
import type * as simulator from "../simulator.js";
import type * as simulatorBenches from "../simulatorBenches.js";
import type * as simulatorEngine from "../simulatorEngine.js";
import type * as simulatorEngineNode from "../simulatorEngineNode.js";
import type * as simulatorPolicies from "../simulatorPolicies.js";
import type * as simulatorPolicyCompiler from "../simulatorPolicyCompiler.js";
import type * as simulatorRuns from "../simulatorRuns.js";
import type * as simulatorTeacher from "../simulatorTeacher.js";
import type * as slackAdmin from "../slackAdmin.js";
import type * as slackAdminOps from "../slackAdminOps.js";
import type * as slackBot from "../slackBot.js";
import type * as slackImageResize from "../slackImageResize.js";
import type * as slackNotifications from "../slackNotifications.js";
import type * as slidesActions from "../slidesActions.js";
import type * as slidesExport from "../slidesExport.js";
import type * as slidesImageSearch from "../slidesImageSearch.js";
import type * as spaces from "../spaces.js";
import type * as staffCapabilities from "../staffCapabilities.js";
import type * as standardsImport from "../standardsImport.js";
import type * as standardsImportHelpers from "../standardsImportHelpers.js";
import type * as standardsMapper from "../standardsMapper.js";
import type * as standardsTree from "../standardsTree.js";
import type * as standingPractice from "../standingPractice.js";
import type * as storyArt from "../storyArt.js";
import type * as storyArtAssets from "../storyArtAssets.js";
import type * as studio from "../studio.js";
import type * as studioFixer from "../studioFixer.js";
import type * as takeHomePlans from "../takeHomePlans.js";
import type * as teachBackGrading from "../teachBackGrading.js";
import type * as teachBacks from "../teachBacks.js";
import type * as teacherAffinities from "../teacherAffinities.js";
import type * as teacherAide from "../teacherAide.js";
import type * as teacherDirectives from "../teacherDirectives.js";
import type * as teacherMasteryOverrides from "../teacherMasteryOverrides.js";
import type * as teacherToday from "../teacherToday.js";
import type * as testDriveFlags from "../testDriveFlags.js";
import type * as tournaments from "../tournaments.js";
import type * as trophyCase from "../trophyCase.js";
import type * as tutorTranscripts from "../tutorTranscripts.js";
import type * as understandings from "../understandings.js";
import type * as understandingsData from "../understandingsData.js";
import type * as unitDesignerStream from "../unitDesignerStream.js";
import type * as unitMaturity from "../unitMaturity.js";
import type * as unitReviews from "../unitReviews.js";
import type * as units from "../units.js";
import type * as usage from "../usage.js";
import type * as users from "../users.js";
import type * as vibecode from "../vibecode.js";
import type * as webActivitySessions from "../webActivitySessions.js";
import type * as webActivitySummary from "../webActivitySummary.js";
import type * as weeklyGoals from "../weeklyGoals.js";
import type * as wholeChild from "../wholeChild.js";
import type * as wholeChildNarratives from "../wholeChildNarratives.js";
import type * as workingLevel from "../workingLevel.js";
import type * as worldBenches from "../worldBenches.js";
import type * as worldEngine from "../worldEngine.js";
import type * as worldEngineNode from "../worldEngineNode.js";
import type * as worldPolicies from "../worldPolicies.js";
import type * as worldPolicyCompiler from "../worldPolicyCompiler.js";
import type * as worldRuns from "../worldRuns.js";
import type * as worldTeacher from "../worldTeacher.js";
import type * as worlds from "../worlds.js";
import type * as youtubeActions from "../youtubeActions.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "__tests__/institutionTestHelpers": typeof __tests___institutionTestHelpers;
  _botRubricFixture: typeof _botRubricFixture;
  academicCalendar: typeof academicCalendar;
  acceleration: typeof acceleration;
  accessGuards: typeof accessGuards;
  accessPreview: typeof accessPreview;
  accountPassword: typeof accountPassword;
  activities: typeof activities;
  activityCompletions: typeof activityCompletions;
  activityResourceActions: typeof activityResourceActions;
  activityResources: typeof activityResources;
  activitySessions: typeof activitySessions;
  adminCloneScholar: typeof adminCloneScholar;
  adminMigrateDossierTeacherBlocks: typeof adminMigrateDossierTeacherBlocks;
  adminTermTools: typeof adminTermTools;
  alerts: typeof alerts;
  analysisHelpers: typeof analysisHelpers;
  appAudiences: typeof appAudiences;
  appStates: typeof appStates;
  artifacts: typeof artifacts;
  assessmentBinder: typeof assessmentBinder;
  "assets/fonts/hankenGroteskBold": typeof assets_fonts_hankenGroteskBold;
  "assets/fonts/hankenGroteskItalic": typeof assets_fonts_hankenGroteskItalic;
  "assets/fonts/hankenGroteskRegular": typeof assets_fonts_hankenGroteskRegular;
  "assets/fonts/hankenGroteskSemiBold": typeof assets_fonts_hankenGroteskSemiBold;
  "assets/fonts/index": typeof assets_fonts_index;
  "assets/fonts/playfairDisplayRegular": typeof assets_fonts_playfairDisplayRegular;
  "assets/seal/index": typeof assets_seal_index;
  "assets/seal/primaryInstitutionSeal": typeof assets_seal_primaryInstitutionSeal;
  assignments: typeof assignments;
  audioActions: typeof audioActions;
  auth: typeof auth;
  badgeArtActions: typeof badgeArtActions;
  badges: typeof badges;
  bakeEval: typeof bakeEval;
  bakePaths: typeof bakePaths;
  bakeUnitFromSeed: typeof bakeUnitFromSeed;
  birthdays: typeof birthdays;
  bugReports: typeof bugReports;
  calculatorLicenses: typeof calculatorLicenses;
  captureStations: typeof captureStations;
  changelog: typeof changelog;
  chatInstruction: typeof chatInstruction;
  chatPractice: typeof chatPractice;
  chatTitles: typeof chatTitles;
  classDigestActions: typeof classDigestActions;
  classDigests: typeof classDigests;
  classResolver: typeof classResolver;
  closureLines: typeof closureLines;
  cohortPractice: typeof cohortPractice;
  conceptAtlas: typeof conceptAtlas;
  concepts: typeof concepts;
  courseNarratives: typeof courseNarratives;
  crons: typeof crons;
  crossDomainConnections: typeof crossDomainConnections;
  curriculumAssistant: typeof curriculumAssistant;
  curriculumExperiments: typeof curriculumExperiments;
  curriculumSim: typeof curriculumSim;
  customApps: typeof customApps;
  dailyRecap: typeof dailyRecap;
  debugBotCheck: typeof debugBotCheck;
  deliverableAssess: typeof deliverableAssess;
  deliverables: typeof deliverables;
  devPilot: typeof devPilot;
  devPurge: typeof devPurge;
  devTools: typeof devTools;
  deviceAppUnlock: typeof deviceAppUnlock;
  deviceLock: typeof deviceLock;
  devicePairing: typeof devicePairing;
  deviceSignOut: typeof deviceSignOut;
  dossier: typeof dossier;
  driveSync: typeof driveSync;
  driveSyncState: typeof driveSyncState;
  edgeStories: typeof edgeStories;
  embedAuth: typeof embedAuth;
  enrollment: typeof enrollment;
  enrollmentImport: typeof enrollmentImport;
  eodCheckin: typeof eodCheckin;
  eodCheckinNarrative: typeof eodCheckinNarrative;
  equipment: typeof equipment;
  equipmentActions: typeof equipmentActions;
  evalExport: typeof evalExport;
  externalApps: typeof externalApps;
  feedMetrics: typeof feedMetrics;
  files: typeof files;
  flairArt: typeof flairArt;
  flairArtActions: typeof flairArtActions;
  flairArtInternal: typeof flairArtInternal;
  gameObserver: typeof gameObserver;
  games: typeof games;
  googleAccounts: typeof googleAccounts;
  googleAccountsActions: typeof googleAccountsActions;
  googleDocsEvents: typeof googleDocsEvents;
  googleDocsEventsActions: typeof googleDocsEventsActions;
  granuleAssessment: typeof granuleAssessment;
  granuleEvidence: typeof granuleEvidence;
  graphemeActions: typeof graphemeActions;
  graphemeInventory: typeof graphemeInventory;
  handoffTranscripts: typeof handoffTranscripts;
  historicalThinkingData: typeof historicalThinkingData;
  http: typeof http;
  impersonation: typeof impersonation;
  improvementTraces: typeof improvementTraces;
  institutionDeletion: typeof institutionDeletion;
  institutionInvites: typeof institutionInvites;
  institutionLifecycle: typeof institutionLifecycle;
  institutions: typeof institutions;
  instruction: typeof instruction;
  instructionVideoHealth: typeof instructionVideoHealth;
  interpretive: typeof interpretive;
  interpretiveHelpers: typeof interpretiveHelpers;
  judgeValidation: typeof judgeValidation;
  keyMoments: typeof keyMoments;
  knowledgeNodes: typeof knowledgeNodes;
  knowledgeState: typeof knowledgeState;
  knowledgeTree: typeof knowledgeTree;
  learningRecord: typeof learningRecord;
  lessons: typeof lessons;
  "lib/access": typeof lib_access;
  "lib/activityCascade": typeof lib_activityCascade;
  "lib/activityCompletionCore": typeof lib_activityCompletionCore;
  "lib/activityCompletionEligibility": typeof lib_activityCompletionEligibility;
  "lib/activityCompletionTool": typeof lib_activityCompletionTool;
  "lib/activityKindTools": typeof lib_activityKindTools;
  "lib/activityPresentationResources": typeof lib_activityPresentationResources;
  "lib/activityResourceDisplay": typeof lib_activityResourceDisplay;
  "lib/activityResourceReachability": typeof lib_activityResourceReachability;
  "lib/activitySessions": typeof lib_activitySessions;
  "lib/aideAttachments": typeof lib_aideAttachments;
  "lib/aideFocus": typeof lib_aideFocus;
  "lib/aideModel": typeof lib_aideModel;
  "lib/aideResolvers": typeof lib_aideResolvers;
  "lib/aideStream": typeof lib_aideStream;
  "lib/aideTools": typeof lib_aideTools;
  "lib/aideUploadMimes": typeof lib_aideUploadMimes;
  "lib/anthropic": typeof lib_anthropic;
  "lib/appAudiences": typeof lib_appAudiences;
  "lib/asnStandardsAdapter": typeof lib_asnStandardsAdapter;
  "lib/assessmentBinder": typeof lib_assessmentBinder;
  "lib/assignmentTools": typeof lib_assignmentTools;
  "lib/atlasEdges": typeof lib_atlasEdges;
  "lib/auth": typeof lib_auth;
  "lib/authConstants": typeof lib_authConstants;
  "lib/authGuards": typeof lib_authGuards;
  "lib/badgeArt": typeof lib_badgeArt;
  "lib/badgeAward": typeof lib_badgeAward;
  "lib/badgeChroma": typeof lib_badgeChroma;
  "lib/bloomRigor": typeof lib_bloomRigor;
  "lib/botTools": typeof lib_botTools;
  "lib/canvasHtml": typeof lib_canvasHtml;
  "lib/cascade": typeof lib_cascade;
  "lib/channels": typeof lib_channels;
  "lib/chromaImage": typeof lib_chromaImage;
  "lib/claimInviteEmail": typeof lib_claimInviteEmail;
  "lib/classResolver": typeof lib_classResolver;
  "lib/claudeFileExtraction": typeof lib_claudeFileExtraction;
  "lib/closureLinePrompt": typeof lib_closureLinePrompt;
  "lib/conceptLabels": typeof lib_conceptLabels;
  "lib/curatedExplorationCatalog": typeof lib_curatedExplorationCatalog;
  "lib/curriculumAccess": typeof lib_curriculumAccess;
  "lib/curriculumDiff": typeof lib_curriculumDiff;
  "lib/curriculumDimensions": typeof lib_curriculumDimensions;
  "lib/curriculumDuplication": typeof lib_curriculumDuplication;
  "lib/curriculumGround": typeof lib_curriculumGround;
  "lib/curriculumImprover": typeof lib_curriculumImprover;
  "lib/curriculumJudge": typeof lib_curriculumJudge;
  "lib/curriculumOptimize": typeof lib_curriculumOptimize;
  "lib/curriculumPreflightResult": typeof lib_curriculumPreflightResult;
  "lib/curriculumProbe": typeof lib_curriculumProbe;
  "lib/curriculumScore": typeof lib_curriculumScore;
  "lib/curriculumSimShared": typeof lib_curriculumSimShared;
  "lib/customAppTools": typeof lib_customAppTools;
  "lib/customFunctions": typeof lib_customFunctions;
  "lib/dailyRecap": typeof lib_dailyRecap;
  "lib/deliverable": typeof lib_deliverable;
  "lib/deploymentConfig": typeof lib_deploymentConfig;
  "lib/deploymentSafety": typeof lib_deploymentSafety;
  "lib/deviceAppProjection": typeof lib_deviceAppProjection;
  "lib/deviceAppUnlockScheduling": typeof lib_deviceAppUnlockScheduling;
  "lib/digestStaleness": typeof lib_digestStaleness;
  "lib/documentKinds": typeof lib_documentKinds;
  "lib/domainTaxonomy": typeof lib_domainTaxonomy;
  "lib/driveAccess": typeof lib_driveAccess;
  "lib/email": typeof lib_email;
  "lib/enrollmentStanding": typeof lib_enrollmentStanding;
  "lib/eodCheckin": typeof lib_eodCheckin;
  "lib/equipmentIdentify": typeof lib_equipmentIdentify;
  "lib/equipmentPhotoBlob": typeof lib_equipmentPhotoBlob;
  "lib/exactTextMatch": typeof lib_exactTextMatch;
  "lib/externalAppIconUrl": typeof lib_externalAppIconUrl;
  "lib/externalAppReach": typeof lib_externalAppReach;
  "lib/externalAppsResolve": typeof lib_externalAppsResolve;
  "lib/externalAppsSeed": typeof lib_externalAppsSeed;
  "lib/externalAppsTools": typeof lib_externalAppsTools;
  "lib/feedMomentum": typeof lib_feedMomentum;
  "lib/fileTextExtraction": typeof lib_fileTextExtraction;
  "lib/fleetHardwareContext": typeof lib_fleetHardwareContext;
  "lib/formInstitutionGate": typeof lib_formInstitutionGate;
  "lib/formRegistry": typeof lib_formRegistry;
  "lib/formReminderEmail": typeof lib_formReminderEmail;
  "lib/gemini": typeof lib_gemini;
  "lib/geomapAssetsTool": typeof lib_geomapAssetsTool;
  "lib/githubSignature": typeof lib_githubSignature;
  "lib/google": typeof lib_google;
  "lib/googleDocsApi": typeof lib_googleDocsApi;
  "lib/googleDocsCommentReply": typeof lib_googleDocsCommentReply;
  "lib/googleDocsCommentTools": typeof lib_googleDocsCommentTools;
  "lib/googleDocsEditor": typeof lib_googleDocsEditor;
  "lib/googleDocsEventsConstants": typeof lib_googleDocsEventsConstants;
  "lib/googleDocsText": typeof lib_googleDocsText;
  "lib/googleDocsTools": typeof lib_googleDocsTools;
  "lib/googleEventsPush": typeof lib_googleEventsPush;
  "lib/googleSlidesApi": typeof lib_googleSlidesApi;
  "lib/googleSlidesEditor": typeof lib_googleSlidesEditor;
  "lib/googleTokens": typeof lib_googleTokens;
  "lib/granules": typeof lib_granules;
  "lib/graphemeAnnotate": typeof lib_graphemeAnnotate;
  "lib/growthStories": typeof lib_growthStories;
  "lib/guardianFormTools": typeof lib_guardianFormTools;
  "lib/healthRecord": typeof lib_healthRecord;
  "lib/healthRecordConfirmationEmail": typeof lib_healthRecordConfirmationEmail;
  "lib/healthRecordTools": typeof lib_healthRecordTools;
  "lib/imageBytes": typeof lib_imageBytes;
  "lib/imageSearch": typeof lib_imageSearch;
  "lib/impersonationConfig": typeof lib_impersonationConfig;
  "lib/independentStudy": typeof lib_independentStudy;
  "lib/inflateRaw": typeof lib_inflateRaw;
  "lib/ingestMimes": typeof lib_ingestMimes;
  "lib/inputModality": typeof lib_inputModality;
  "lib/institutionInvites": typeof lib_institutionInvites;
  "lib/institutionLens": typeof lib_institutionLens;
  "lib/institutionPromptProfile": typeof lib_institutionPromptProfile;
  "lib/institutionTime": typeof lib_institutionTime;
  "lib/judgeCorrelation": typeof lib_judgeCorrelation;
  "lib/knowledgeNodeEdges": typeof lib_knowledgeNodeEdges;
  "lib/knowledgeNodeResolver": typeof lib_knowledgeNodeResolver;
  "lib/knowledgeTreeData": typeof lib_knowledgeTreeData;
  "lib/knowledgeTreeFrontier": typeof lib_knowledgeTreeFrontier;
  "lib/labelAgreement": typeof lib_labelAgreement;
  "lib/leapSeeds": typeof lib_leapSeeds;
  "lib/magicAnnotations": typeof lib_magicAnnotations;
  "lib/magicLinkEmail": typeof lib_magicLinkEmail;
  "lib/managedDeviceClaimState": typeof lib_managedDeviceClaimState;
  "lib/managedNativeApps": typeof lib_managedNativeApps;
  "lib/masterScheduleTools": typeof lib_masterScheduleTools;
  "lib/messageLinkPreview": typeof lib_messageLinkPreview;
  "lib/metaBlocks": typeof lib_metaBlocks;
  "lib/models": typeof lib_models;
  "lib/momentInterestingness": typeof lib_momentInterestingness;
  "lib/moments/storyMomentPolicy": typeof lib_moments_storyMomentPolicy;
  "lib/nodeDepthHelpers": typeof lib_nodeDepthHelpers;
  "lib/oauthCrypto": typeof lib_oauthCrypto;
  "lib/observerShared": typeof lib_observerShared;
  "lib/parentAidePrompt": typeof lib_parentAidePrompt;
  "lib/parentMessageChannels": typeof lib_parentMessageChannels;
  "lib/parentMessageEmail": typeof lib_parentMessageEmail;
  "lib/passkeyConfig": typeof lib_passkeyConfig;
  "lib/passwordCrypto": typeof lib_passwordCrypto;
  "lib/pca": typeof lib_pca;
  "lib/pcm": typeof lib_pcm;
  "lib/pdfSegments": typeof lib_pdfSegments;
  "lib/pdfSubstitute": typeof lib_pdfSubstitute;
  "lib/physicalEnvTools": typeof lib_physicalEnvTools;
  "lib/portfolioAttributions": typeof lib_portfolioAttributions;
  "lib/portfolioStatus": typeof lib_portfolioStatus;
  "lib/practice/answerShape": typeof lib_practice_answerShape;
  "lib/practice/answers": typeof lib_practice_answers;
  "lib/practice/applicationEligibility": typeof lib_practice_applicationEligibility;
  "lib/practice/calibration": typeof lib_practice_calibration;
  "lib/practice/chatInstruction": typeof lib_practice_chatInstruction;
  "lib/practice/chatPractice": typeof lib_practice_chatPractice;
  "lib/practice/checkpointFocus": typeof lib_practice_checkpointFocus;
  "lib/practice/countableReconstruct": typeof lib_practice_countableReconstruct;
  "lib/practice/coverage": typeof lib_practice_coverage;
  "lib/practice/crossDomainSeeds": typeof lib_practice_crossDomainSeeds;
  "lib/practice/dialogueStretch": typeof lib_practice_dialogueStretch;
  "lib/practice/dispatchCompletion": typeof lib_practice_dispatchCompletion;
  "lib/practice/domainMapStatus": typeof lib_practice_domainMapStatus;
  "lib/practice/domainRetention": typeof lib_practice_domainRetention;
  "lib/practice/domains": typeof lib_practice_domains;
  "lib/practice/errorFlags": typeof lib_practice_errorFlags;
  "lib/practice/errorPatterns": typeof lib_practice_errorPatterns;
  "lib/practice/evalExpr": typeof lib_practice_evalExpr;
  "lib/practice/factFluency": typeof lib_practice_factFluency;
  "lib/practice/factSprint": typeof lib_practice_factSprint;
  "lib/practice/fadedSteps": typeof lib_practice_fadedSteps;
  "lib/practice/fastMath": typeof lib_practice_fastMath;
  "lib/practice/fastMathRead": typeof lib_practice_fastMathRead;
  "lib/practice/frontierGrade": typeof lib_practice_frontierGrade;
  "lib/practice/gameBeats": typeof lib_practice_gameBeats;
  "lib/practice/gateEval": typeof lib_practice_gateEval;
  "lib/practice/graphValidation": typeof lib_practice_graphValidation;
  "lib/practice/handoff": typeof lib_practice_handoff;
  "lib/practice/implicitCredit": typeof lib_practice_implicitCredit;
  "lib/practice/instructionEntries": typeof lib_practice_instructionEntries;
  "lib/practice/instructionVerify": typeof lib_practice_instructionVerify;
  "lib/practice/latencyStats": typeof lib_practice_latencyStats;
  "lib/practice/manipulativeKindUsage": typeof lib_practice_manipulativeKindUsage;
  "lib/practice/mapping": typeof lib_practice_mapping;
  "lib/practice/mathPlan": typeof lib_practice_mathPlan;
  "lib/practice/mathSkillsNarrative": typeof lib_practice_mathSkillsNarrative;
  "lib/practice/mixedQueue": typeof lib_practice_mixedQueue;
  "lib/practice/padHints": typeof lib_practice_padHints;
  "lib/practice/paramHealth": typeof lib_practice_paramHealth;
  "lib/practice/placement": typeof lib_practice_placement;
  "lib/practice/plainText": typeof lib_practice_plainText;
  "lib/practice/promptVisual": typeof lib_practice_promptVisual;
  "lib/practice/remediation": typeof lib_practice_remediation;
  "lib/practice/revealLine": typeof lib_practice_revealLine;
  "lib/practice/reveals": typeof lib_practice_reveals;
  "lib/practice/scheduler": typeof lib_practice_scheduler;
  "lib/practice/scholarLatencyBaseline": typeof lib_practice_scholarLatencyBaseline;
  "lib/practice/seedSpawn": typeof lib_practice_seedSpawn;
  "lib/practice/segments": typeof lib_practice_segments;
  "lib/practice/servable": typeof lib_practice_servable;
  "lib/practice/serve": typeof lib_practice_serve;
  "lib/practice/session": typeof lib_practice_session;
  "lib/practice/spiralBreaker": typeof lib_practice_spiralBreaker;
  "lib/practice/storyDigest": typeof lib_practice_storyDigest;
  "lib/practice/storyOpen": typeof lib_practice_storyOpen;
  "lib/practice/storyRegistry": typeof lib_practice_storyRegistry;
  "lib/practice/stuckAlertBody": typeof lib_practice_stuckAlertBody;
  "lib/practice/stuckAlertPrompt": typeof lib_practice_stuckAlertPrompt;
  "lib/practice/summits": typeof lib_practice_summits;
  "lib/practice/templates": typeof lib_practice_templates;
  "lib/practice/tuneup": typeof lib_practice_tuneup;
  "lib/practice/verify": typeof lib_practice_verify;
  "lib/practice/weeklyMathTopics": typeof lib_practice_weeklyMathTopics;
  "lib/practice/workedStepGen": typeof lib_practice_workedStepGen;
  "lib/practiceAtlasLayout": typeof lib_practiceAtlasLayout;
  "lib/practiceDigest": typeof lib_practiceDigest;
  "lib/practicePoolTools": typeof lib_practicePoolTools;
  "lib/practiceSkillTreeTools": typeof lib_practiceSkillTreeTools;
  "lib/prepBlock": typeof lib_prepBlock;
  "lib/primaryInstitution": typeof lib_primaryInstitution;
  "lib/primaryInstitutionPrintIdentity": typeof lib_primaryInstitutionPrintIdentity;
  "lib/primaryInstitutionPromptProfile": typeof lib_primaryInstitutionPromptProfile;
  "lib/printRelayHttp": typeof lib_printRelayHttp;
  "lib/profileImage": typeof lib_profileImage;
  "lib/programGroupAccess": typeof lib_programGroupAccess;
  "lib/programGuestWork": typeof lib_programGuestWork;
  "lib/programHandoutAccess": typeof lib_programHandoutAccess;
  "lib/promptVersion": typeof lib_promptVersion;
  "lib/pushes": typeof lib_pushes;
  "lib/questLifecycle": typeof lib_questLifecycle;
  "lib/readingLevels": typeof lib_readingLevels;
  "lib/rehearsalBudget": typeof lib_rehearsalBudget;
  "lib/resendInbound": typeof lib_resendInbound;
  "lib/roles": typeof lib_roles;
  "lib/rooms": typeof lib_rooms;
  "lib/rosterPulse": typeof lib_rosterPulse;
  "lib/rubricScoreTool": typeof lib_rubricScoreTool;
  "lib/sandbox": typeof lib_sandbox;
  "lib/scheduleMirror": typeof lib_scheduleMirror;
  "lib/schedulePlacementIdentity": typeof lib_schedulePlacementIdentity;
  "lib/scholarCodeTools": typeof lib_scholarCodeTools;
  "lib/scholarCredential": typeof lib_scholarCredential;
  "lib/scholarEnrollment": typeof lib_scholarEnrollment;
  "lib/scholarGroupMembership": typeof lib_scholarGroupMembership;
  "lib/scholarGroupUnlocks": typeof lib_scholarGroupUnlocks;
  "lib/scholarIdeaTools": typeof lib_scholarIdeaTools;
  "lib/scholarMatch": typeof lib_scholarMatch;
  "lib/scholarParticipationTooling": typeof lib_scholarParticipationTooling;
  "lib/scholarPronouns": typeof lib_scholarPronouns;
  "lib/scholarReadPolicy": typeof lib_scholarReadPolicy;
  "lib/scholarReadTools": typeof lib_scholarReadTools;
  "lib/scholarReads": typeof lib_scholarReads;
  "lib/scholarSafeText": typeof lib_scholarSafeText;
  "lib/scholarWriteTools": typeof lib_scholarWriteTools;
  "lib/schoolDay": typeof lib_schoolDay;
  "lib/schoolDays": typeof lib_schoolDays;
  "lib/schoolMediaConsent": typeof lib_schoolMediaConsent;
  "lib/seedLabel": typeof lib_seedLabel;
  "lib/seeds": typeof lib_seeds;
  "lib/selSynthesisPrompt": typeof lib_selSynthesisPrompt;
  "lib/serviceAccount": typeof lib_serviceAccount;
  "lib/sessionActivitySetup": typeof lib_sessionActivitySetup;
  "lib/sessionRecap": typeof lib_sessionRecap;
  "lib/simulatorRedTeam": typeof lib_simulatorRedTeam;
  "lib/simulatorRunBudget": typeof lib_simulatorRunBudget;
  "lib/simulatorRunEvidence": typeof lib_simulatorRunEvidence;
  "lib/simulatorTemplatesCatalog": typeof lib_simulatorTemplatesCatalog;
  "lib/skyField": typeof lib_skyField;
  "lib/skyMuseum": typeof lib_skyMuseum;
  "lib/skySeedSelection": typeof lib_skySeedSelection;
  "lib/slackApi": typeof lib_slackApi;
  "lib/slackCanvasReport": typeof lib_slackCanvasReport;
  "lib/slackLists": typeof lib_slackLists;
  "lib/slackPermalink": typeof lib_slackPermalink;
  "lib/slackSignature": typeof lib_slackSignature;
  "lib/slackText": typeof lib_slackText;
  "lib/slackTools": typeof lib_slackTools;
  "lib/slackTranscript": typeof lib_slackTranscript;
  "lib/slideImageFidelity": typeof lib_slideImageFidelity;
  "lib/slidesMedia": typeof lib_slidesMedia;
  "lib/slidesRender": typeof lib_slidesRender;
  "lib/specialDeliveryEditorial": typeof lib_specialDeliveryEditorial;
  "lib/specialDeliveryInsertShared": typeof lib_specialDeliveryInsertShared;
  "lib/specialDeliveryPrint": typeof lib_specialDeliveryPrint;
  "lib/specialDeliverySketchImage": typeof lib_specialDeliverySketchImage;
  "lib/staffCapabilities": typeof lib_staffCapabilities;
  "lib/standardNotation": typeof lib_standardNotation;
  "lib/standardStrand": typeof lib_standardStrand;
  "lib/suggestionTools": typeof lib_suggestionTools;
  "lib/teachBack": typeof lib_teachBack;
  "lib/testDriveReplay": typeof lib_testDriveReplay;
  "lib/textToTitle": typeof lib_textToTitle;
  "lib/themeIconArt": typeof lib_themeIconArt;
  "lib/thumbnail": typeof lib_thumbnail;
  "lib/toolActivityGroups": typeof lib_toolActivityGroups;
  "lib/toolLabels": typeof lib_toolLabels;
  "lib/tutorClosingGuidance": typeof lib_tutorClosingGuidance;
  "lib/tutorSessionTools": typeof lib_tutorSessionTools;
  "lib/unitAccess": typeof lib_unitAccess;
  "lib/unitDesignSerializer": typeof lib_unitDesignSerializer;
  "lib/unitDesignerTools": typeof lib_unitDesignerTools;
  "lib/unitMaturity": typeof lib_unitMaturity;
  "lib/usage": typeof lib_usage;
  "lib/usageReport": typeof lib_usageReport;
  "lib/username": typeof lib_username;
  "lib/webActivityTarget": typeof lib_webActivityTarget;
  "lib/webSessionSummary": typeof lib_webSessionSummary;
  libraryCards: typeof libraryCards;
  llmBudget: typeof llmBudget;
  magicAnnotations: typeof magicAnnotations;
  managedDeviceClaims: typeof managedDeviceClaims;
  manipulativeThemeIconActions: typeof manipulativeThemeIconActions;
  manipulativeThemeIcons: typeof manipulativeThemeIcons;
  mapGates: typeof mapGates;
  masterSchedule: typeof masterSchedule;
  masteryObservations: typeof masteryObservations;
  masteryReDerive: typeof masteryReDerive;
  mathFocus: typeof mathFocus;
  mathPlans: typeof mathPlans;
  mathPortrait: typeof mathPortrait;
  mcp: typeof mcp;
  mcpOauth: typeof mcpOauth;
  memberships: typeof memberships;
  messageFlags: typeof messageFlags;
  messageLinkPreviewCache: typeof messageLinkPreviewCache;
  messageLinkPreviews: typeof messageLinkPreviews;
  messages: typeof messages;
  metaChat: typeof metaChat;
  metaObserver: typeof metaObserver;
  metaPrompts: typeof metaPrompts;
  nativeClientHeartbeat: typeof nativeClientHeartbeat;
  ngssData: typeof ngssData;
  nodeDepth: typeof nodeDepth;
  nodeNeighbourhood: typeof nodeNeighbourhood;
  notifications: typeof notifications;
  observations: typeof observations;
  observer: typeof observer;
  onboarding: typeof onboarding;
  onboardingData: typeof onboardingData;
  openMap: typeof openMap;
  parentChat: typeof parentChat;
  parentMessageSend: typeof parentMessageSend;
  parentMessageSlack: typeof parentMessageSlack;
  parentMessages: typeof parentMessages;
  parents: typeof parents;
  passkeys: typeof passkeys;
  personas: typeof personas;
  perspectives: typeof perspectives;
  physicalEnvAide: typeof physicalEnvAide;
  physicalTasks: typeof physicalTasks;
  portfolio: typeof portfolio;
  portfolioActions: typeof portfolioActions;
  portfolioAssess: typeof portfolioAssess;
  portfolioIngestions: typeof portfolioIngestions;
  portfolioMaterialize: typeof portfolioMaterialize;
  portfolioRefile: typeof portfolioRefile;
  portfolioRefileMutations: typeof portfolioRefileMutations;
  portfolioRepair: typeof portfolioRepair;
  portfolioThumbs: typeof portfolioThumbs;
  practiceAtlas: typeof practiceAtlas;
  practiceAtlasData: typeof practiceAtlasData;
  practiceCalibration: typeof practiceCalibration;
  practiceDialogue: typeof practiceDialogue;
  practiceDigest: typeof practiceDigest;
  practiceGames: typeof practiceGames;
  practiceGen: typeof practiceGen;
  practiceHintActions: typeof practiceHintActions;
  practiceInstruments: typeof practiceInstruments;
  practiceItemPool: typeof practiceItemPool;
  practiceMoments: typeof practiceMoments;
  practicePadHints: typeof practicePadHints;
  practiceSkills: typeof practiceSkills;
  practiceStuckAlert: typeof practiceStuckAlert;
  practiceTextCleanup: typeof practiceTextCleanup;
  practiceTuneups: typeof practiceTuneups;
  practiceWorkImages: typeof practiceWorkImages;
  processState: typeof processState;
  processes: typeof processes;
  prompts: typeof prompts;
  pushes: typeof pushes;
  qualityLabeling: typeof qualityLabeling;
  quests: typeof quests;
  readingLevelAnalysis: typeof readingLevelAnalysis;
  realtimeTranscription: typeof realtimeTranscription;
  reportingPeriods: typeof reportingPeriods;
  roomCues: typeof roomCues;
  rooms: typeof rooms;
  rounds: typeof rounds;
  sandboxActions: typeof sandboxActions;
  scholarActivityAngles: typeof scholarActivityAngles;
  scholarApps: typeof scholarApps;
  scholarDocumentActions: typeof scholarDocumentActions;
  scholarDocumentProposalActions: typeof scholarDocumentProposalActions;
  scholarDocumentProposals: typeof scholarDocumentProposals;
  scholarDocuments: typeof scholarDocuments;
  scholarGoals: typeof scholarGoals;
  scholarGroups: typeof scholarGroups;
  scholarHealthRecords: typeof scholarHealthRecords;
  scholarPlate: typeof scholarPlate;
  scholarSuggestions: typeof scholarSuggestions;
  scholarUnitBadges: typeof scholarUnitBadges;
  scholars: typeof scholars;
  "seed/algebra1Graph": typeof seed_algebra1Graph;
  "seed/assessmentDemo": typeof seed_assessmentDemo;
  "seed/cooperationConflict": typeof seed_cooperationConflict;
  "seed/devPersonas": typeof seed_devPersonas;
  "seed/discreteMathGraph": typeof seed_discreteMathGraph;
  "seed/earlyAlgebraGraph": typeof seed_earlyAlgebraGraph;
  "seed/fractionArithmeticGraph": typeof seed_fractionArithmeticGraph;
  "seed/gamesDemo": typeof seed_gamesDemo;
  "seed/geographyQuests": typeof seed_geographyQuests;
  "seed/geometryMeasurementGraph": typeof seed_geometryMeasurementGraph;
  "seed/institutions": typeof seed_institutions;
  "seed/instructionSeed": typeof seed_instructionSeed;
  "seed/integersCoordinatesGraph": typeof seed_integersCoordinatesGraph;
  "seed/launchpadDemo": typeof seed_launchpadDemo;
  "seed/physicalEnvironment": typeof seed_physicalEnvironment;
  "seed/probabilityGraph": typeof seed_probabilityGraph;
  "seed/prodBlockSchedule": typeof seed_prodBlockSchedule;
  "seed/programFamilies": typeof seed_programFamilies;
  "seed/ratioProportionPercentGraph": typeof seed_ratioProportionPercentGraph;
  "seed/rich/badgeArtAssets": typeof seed_rich_badgeArtAssets;
  "seed/rich/chat": typeof seed_rich_chat;
  "seed/rich/curriculum": typeof seed_rich_curriculum;
  "seed/rich/execution": typeof seed_rich_execution;
  "seed/rich/index": typeof seed_rich_index;
  "seed/rich/observation": typeof seed_rich_observation;
  "seed/rich/practice": typeof seed_rich_practice;
  "seed/rich/robotics": typeof seed_rich_robotics;
  "seed/rich/roster": typeof seed_rich_roster;
  "seed/rich/schedule": typeof seed_rich_schedule;
  "seed/rich/sims": typeof seed_rich_sims;
  "seed/rich/types": typeof seed_rich_types;
  "seed/rosterPulseDemo": typeof seed_rosterPulseDemo;
  "seed/sampleReports": typeof seed_sampleReports;
  "seed/storyArtAssets": typeof seed_storyArtAssets;
  "seed/stretchItems": typeof seed_stretchItems;
  "seed/systemsAgents": typeof seed_systemsAgents;
  "seed/wholeNumberArithmeticGraph": typeof seed_wholeNumberArithmeticGraph;
  seedAiLiteracyUnits: typeof seedAiLiteracyUnits;
  seedAtlasDemo: typeof seedAtlasDemo;
  seedAutoRubricForTesting: typeof seedAutoRubricForTesting;
  seedBadgeArt: typeof seedBadgeArt;
  seedData: typeof seedData;
  seedDigestDemo: typeof seedDigestDemo;
  seedMasterSchedule: typeof seedMasterSchedule;
  seedMisconceptionForTesting: typeof seedMisconceptionForTesting;
  seedProbabilityStrand: typeof seedProbabilityStrand;
  seedProdUnits: typeof seedProdUnits;
  seedProdUnitsData: typeof seedProdUnitsData;
  seedRichCohort: typeof seedRichCohort;
  seedRoboticsMedia: typeof seedRoboticsMedia;
  seedRubricActivityForTesting: typeof seedRubricActivityForTesting;
  seedTranscribeDemoForTesting: typeof seedTranscribeDemoForTesting;
  seedUnitForTesting: typeof seedUnitForTesting;
  seeds: typeof seeds;
  selSyntheses: typeof selSyntheses;
  selSynthesisActions: typeof selSynthesisActions;
  selSynthesisCron: typeof selSynthesisCron;
  sessionContextHelpers: typeof sessionContextHelpers;
  sessionHelpers: typeof sessionHelpers;
  sessionSignals: typeof sessionSignals;
  sessionStreamHelpers: typeof sessionStreamHelpers;
  sessionTitles: typeof sessionTitles;
  sessions: typeof sessions;
  shareBack: typeof shareBack;
  shareBackActions: typeof shareBackActions;
  simplemdm: typeof simplemdm;
  simulator: typeof simulator;
  simulatorBenches: typeof simulatorBenches;
  simulatorEngine: typeof simulatorEngine;
  simulatorEngineNode: typeof simulatorEngineNode;
  simulatorPolicies: typeof simulatorPolicies;
  simulatorPolicyCompiler: typeof simulatorPolicyCompiler;
  simulatorRuns: typeof simulatorRuns;
  simulatorTeacher: typeof simulatorTeacher;
  slackAdmin: typeof slackAdmin;
  slackAdminOps: typeof slackAdminOps;
  slackBot: typeof slackBot;
  slackImageResize: typeof slackImageResize;
  slackNotifications: typeof slackNotifications;
  slidesActions: typeof slidesActions;
  slidesExport: typeof slidesExport;
  slidesImageSearch: typeof slidesImageSearch;
  spaces: typeof spaces;
  staffCapabilities: typeof staffCapabilities;
  standardsImport: typeof standardsImport;
  standardsImportHelpers: typeof standardsImportHelpers;
  standardsMapper: typeof standardsMapper;
  standardsTree: typeof standardsTree;
  standingPractice: typeof standingPractice;
  storyArt: typeof storyArt;
  storyArtAssets: typeof storyArtAssets;
  studio: typeof studio;
  studioFixer: typeof studioFixer;
  takeHomePlans: typeof takeHomePlans;
  teachBackGrading: typeof teachBackGrading;
  teachBacks: typeof teachBacks;
  teacherAffinities: typeof teacherAffinities;
  teacherAide: typeof teacherAide;
  teacherDirectives: typeof teacherDirectives;
  teacherMasteryOverrides: typeof teacherMasteryOverrides;
  teacherToday: typeof teacherToday;
  testDriveFlags: typeof testDriveFlags;
  tournaments: typeof tournaments;
  trophyCase: typeof trophyCase;
  tutorTranscripts: typeof tutorTranscripts;
  understandings: typeof understandings;
  understandingsData: typeof understandingsData;
  unitDesignerStream: typeof unitDesignerStream;
  unitMaturity: typeof unitMaturity;
  unitReviews: typeof unitReviews;
  units: typeof units;
  usage: typeof usage;
  users: typeof users;
  vibecode: typeof vibecode;
  webActivitySessions: typeof webActivitySessions;
  webActivitySummary: typeof webActivitySummary;
  weeklyGoals: typeof weeklyGoals;
  wholeChild: typeof wholeChild;
  wholeChildNarratives: typeof wholeChildNarratives;
  workingLevel: typeof workingLevel;
  worldBenches: typeof worldBenches;
  worldEngine: typeof worldEngine;
  worldEngineNode: typeof worldEngineNode;
  worldPolicies: typeof worldPolicies;
  worldPolicyCompiler: typeof worldPolicyCompiler;
  worldRuns: typeof worldRuns;
  worldTeacher: typeof worldTeacher;
  worlds: typeof worlds;
  youtubeActions: typeof youtubeActions;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
};
