#!/usr/bin/env node
/**
 * Bundles the offline Studio document for the web and native WebView hosts.
 */
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const shellPath = join(root, "studio/shell.html");
const entryPoint = join(root, "studio/src/main.ts");
const outputPath = join(root, "shared/studioDocument.generated.ts");
const bundleSlot = '<script type="module">/*BUNDLE*/</script>';

function escapeScriptEndTags(bundle) {
  return bundle.replace(/<\/script/gi, "<\\/script");
}

export async function buildStudioDocument() {
  const [shell, result] = await Promise.all([
    readFile(shellPath, "utf8"),
    esbuild.build({
      bundle: true,
      entryPoints: [entryPoint],
      format: "esm",
      minify: true,
      platform: "browser",
      sourcemap: false,
      target: "safari17",
      write: false,
    }),
  ]);

  if (shell.split(bundleSlot).length !== 2) {
    throw new Error(
      `${shellPath} must contain exactly one <script type="module">/*BUNDLE*/</script> slot.`,
    );
  }

  const bundle = escapeScriptEndTags(result.outputFiles[0].text);
  const wrapped = `<script type="module">${bundle}</script>`;
  // A replacer FUNCTION, not a string: a string replacement treats `$&`, `$'`
  // and friends as substitution patterns, and minified JS is full of `$`.
  // Passing the bundle directly spliced the tail of the shell back into the
  // middle of the code — a corrupt document that still built cleanly.
  const document = shell.replace(bundleSlot, () => wrapped);
  const expected = shell.length - bundleSlot.length + wrapped.length;
  if (document.length !== expected) {
    throw new Error(
      `Substitution corrupted the document (${document.length} bytes, expected ${expected}).`,
    );
  }
  const hash = createHash("sha256").update(document).digest("hex").slice(0, 16);
  const generated = `// GENERATED by studio/build.mjs — run \`pnpm studio:build\`; do not edit by hand.
// prettier-ignore
export const STUDIO_DOCUMENT_HTML = ${JSON.stringify(document)};
export const STUDIO_DOCUMENT_HASH = "${hash}";
`;

  return { bundle, document, generated, hash };
}

async function main() {
  const { bundle, document, hash, generated } = await buildStudioDocument();
  await writeFile(outputPath, generated);
  console.log(
    `Wrote shared/studioDocument.generated.ts (${bundle.length} JS bytes, ${document.length} document bytes, hash ${hash})`,
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
