// Bot DRY Layer 2 — shared building blocks for the three Curriculum
// Bot streams (global aide, unit designer, quest designer).
//
// Layer 1 (lib/deliverable.ts) collapsed deliverable normalization +
// the "online needs deliverable" guard. Layer 2 (this file) collapses
// the *bot tool surface*: the JSON schema fragments that appear in
// every tool that accepts a deliverable, the parsing logic that turns
// the bot's tool-call input into upsertInternal args, and the
// canonical error-recovery message the bot reads when the guard
// throws.
//
// Anything that recurs across ≥2 of the three streams lives here.
// Stream-specific lookups (find-lesson-by-title vs lessonId, quest
// linking, etc.) stay in the streams.

import type { DeliverableCriterion } from "./deliverable";

/**
 * Anthropic's first-party server-side web search tool. Runs entirely on
 * Anthropic's infrastructure — no `run()` handler: the model issues a query,
 * Anthropic executes the search and feeds cited results back inline within the
 * same streamed turn. Shared so every staff aide (the global Curriculum
 * Assistant, the Slack bot, the unit-designer Curriculum Bot) exposes the same
 * capability for grounding lessons/answers in current events and facts past the
 * model's training cutoff. `max_uses` caps the searches per turn so a single
 * request can't run away.
 *
 * Pinned to `_20250305`, NOT the newer `_20260209` ("dynamic filtering")
 * version: the `_20260209` web tools run their result filtering in a
 * server-side code-execution container, and the pinned `@anthropic-ai/sdk`
 * (0.91.1) `beta.messages.toolRunner` does NOT thread the resulting
 * `container_id` onto the continuation request — so the turn AFTER a search
 * 400s with "container_id is required when there are pending tool uses
 * generated by code execution with tools." `_20250305` runs no container, so
 * the loop stays clean. Fix-forward (unblock the SDK upgrade — see TODO.html
 * "Security / Dependency Upgrades" — then move back to `_20260209` for dynamic
 * filtering) is tracked in TODO.html#anthropic-sdk-pin.
 *
 * Typed `as const` (not `BetaWebSearchTool20250305`) on purpose: this file is
 * imported by the edge-bundled tool assemblers, which deliberately avoid any
 * value import of `@anthropic-ai/sdk` (it drags `node:*` in — see the SDK-pin
 * note in aideStream.ts). The literal is structurally a `BetaWebSearchTool…`,
 * so the toolRunner `tools` array accepts it without the type import.
 */
export const WEB_SEARCH_TOOL = {
  type: "web_search_20250305",
  name: "web_search",
  max_uses: 5,
} as const;

/**
 * Anthropic's first-party server-side web FETCH tool — the companion to
 * WEB_SEARCH_TOOL. Search finds pages; fetch reads the full content of a
 * SPECIFIC url. The staff workflow: a teacher pastes a link (an article, a
 * standards page, a resource) and says "build a unit around this" — the model
 * fetches it and grounds the work in the real text. Also Anthropic-hosted, no
 * `run()` handler.
 *
 * `max_content_tokens` caps how much of a fetched page lands in context so one
 * giant page can't blow up the aide's input budget; `max_uses` caps fetches per
 * turn. Citations are left off (default) — the aide streams plain markdown and
 * the runner doesn't render citation blocks, matching WEB_SEARCH_TOOL.
 *
 * Pinned to `_20250910`, NOT `_20260209`, for the same toolRunner /
 * container_id reason documented on WEB_SEARCH_TOOL above (the `_20260209`
 * fetch tool also runs in a code-execution container the pinned SDK can't
 * thread). `_20250910` is field-compatible (same `max_uses` /
 * `max_content_tokens`). Fix-forward: TODO.html#anthropic-sdk-pin.
 *
 * Same `as const` rationale as WEB_SEARCH_TOOL (no value import of the SDK).
 */
export const WEB_FETCH_TOOL = {
  type: "web_fetch_20250910",
  name: "web_fetch",
  max_uses: 5,
  max_content_tokens: 50000,
} as const;

/**
 * JSON-schema fragment for the `deliverable` property in any
 * bot-facing tool that creates or updates an activity. Embed
 * inline:
 *
 *   inputSchema: {
 *     type: "object" as const,
 *     properties: {
 *       lessonId: { type: "string", description: "..." },
 *       title: ...,
 *       deliverable: deliverableSchemaFragment(),
 *     },
 *     required: ["lessonId", "title", "deliverable"],
 *   }
 *
 * Single source of truth — every bot sees the same deliverable
 * shape. The `required` keys list inside is included.
 */
export function deliverableSchemaFragment() {
  return {
    type: "object" as const,
    description:
      "Private quality map for the tutor. It does not gate activity completion. When a scholar fully demonstrates a criterion, it becomes permanent scholar-visible flair with its label and description shown together; half/not-full verdicts remain private. Two modes: 'manual' (you author the criteria array, same for every scholar) or 'auto' (the system generates criteria per-scholar at project creation, calibrated to their reading level — pass `notes` describing intent). Prefer 'auto' when the activity will be done by a wide age/reading-level range; prefer 'manual' for a tight grade band.",
    properties: {
      kind: {
        type: "string" as const,
        enum: ["photo", "artifact", "slides", "text", "audio", "map"] as const,
        description:
          "Form factor of the deliverable. 'text' for written work, 'artifact' for code/markdown documents, 'photo' for image submissions, 'slides' for decks, 'audio' for spoken work, 'map' when the map itself is the product scholars check or send.",
      },
      prompt: {
        type: "string" as const,
        description:
          "Scholar-facing description of what they should produce. 1-2 sentences. Speak to the scholar.",
      },
      mode: {
        type: "string" as const,
        enum: ["manual", "auto"] as const,
        description:
          "'manual' = you provide the criteria array. 'auto' = the AI generates criteria per scholar at project start (using `notes` + reading level).",
      },
      notes: {
        type: "string" as const,
        description:
          "Auto-mode only: prose describing the quality bar, dimensions that matter, pitfalls to flag. The AI uses this + the scholar's reading level to generate calibrated criteria.",
      },
      criteria: {
        type: "array" as const,
        description:
          "Manual mode: 3-6 dimensional rubric items, each { label, description }. Auto mode: pass [] (the generator fills it in per scholar).",
        items: {
          type: "object" as const,
          properties: {
            label: {
              type: "string" as const,
              description:
                "Short criterion name, 1-4 words. E.g. 'Specificity', 'Mechanics', 'Beginning, middle, end'.",
            },
            description: {
              type: "string" as const,
              description:
                "Concrete standard for this criterion. State what counts as 'full' and what triggers 'half' or 'not'. Include failure modes explicitly.",
            },
          },
          required: ["label", "description"] as const,
        },
      },
    },
    required: ["kind", "prompt", "mode", "criteria"] as const,
  };
}

/**
 * The raw shape a bot tool-call's `deliverable` input arrives in.
 * Always normalize via `parseDeliverableArg` before passing
 * downstream — that gives you the canonical upsertInternal-compatible
 * shape (and explicitly enables the criteria-id auto-slugifier by
 * blanking the id field).
 */
export interface RawBotDeliverable {
  kind: "photo" | "artifact" | "slides" | "text" | "audio" | "map";
  prompt: string;
  mode?: "manual" | "auto";
  notes?: string;
  criteria?: Array<{ label: string; description: string }>;
}

/**
 * Convert a bot tool-call's deliverable input into the shape
 * `activities.upsertInternal` expects. Returns undefined when the
 * caller didn't pass a deliverable (offline activities, kickoffs,
 * etc.). Defaults mode to "manual" — bots that want auto mode have
 * to ask for it explicitly.
 */
export function parseDeliverableArg(
  raw: RawBotDeliverable | undefined,
):
  | {
      kind: RawBotDeliverable["kind"];
      prompt: string;
      mode: "manual" | "auto";
      notes?: string;
      criteria: DeliverableCriterion[];
    }
  | undefined {
  if (!raw) return undefined;
  const mode = raw.mode ?? "manual";
  return {
    kind: raw.kind,
    prompt: raw.prompt,
    mode,
    notes: raw.notes,
    // Blank id triggers the normalizer's slug-from-label path.
    criteria: (raw.criteria ?? []).map((c) => ({
      id: "",
      label: c.label,
      description: c.description,
    })),
  };
}

/**
 * JSON-schema fragment for the `advanceRubric` property in any
 * bot-facing tool that creates or updates an activity. The advance
 * rubric is the "grade the CONVERSATION, not a document" primitive:
 * same criteria shape as a deliverable, but the tutor scores it
 * against the discussion + interactive surface (map pins, etc.) and a
 * pass marks the activity complete — with NO document for the scholar
 * to fill in. This is the right exit bar for an interactive/discovery
 * activity (a map discovery sequence, a Socratic discussion) where the
 * learning happens in the talking, not in a produced artifact. A map that is
 * itself the product uses a map deliverable instead.
 *
 * Single source of truth — every bot sees the same advance-rubric shape.
 */
export function advanceRubricSchemaFragment() {
  return {
    type: "object" as const,
    description:
      "Conversation exit criteria for an ONLINE activity that produces NO artifact — the tutor grades the scholar's talk + interactions (map pins, predictions, explanations) against these criteria, and a full pass marks the activity complete. Use this INSTEAD of a `deliverable` when the point is what the scholar says and does. If the map itself is the product the scholar should repeatedly check or send, use a deliverable with kind 'map'. Never attach BOTH.",
    properties: {
      criteria: {
        type: "array" as const,
        description:
          "3-6 dimensional criteria, each { label, description }. Grade what the scholar demonstrates IN CONVERSATION (located the requested places, predicted before revealing, explained the pattern in their own words, transferred it to a new case) — not a produced artifact. State what counts as 'full' vs 'half'/'not'.",
        items: {
          type: "object" as const,
          properties: {
            label: {
              type: "string" as const,
              description:
                "Short criterion name, 1-4 words. E.g. 'Located the capitals', 'Explained the why', 'Transferred the pattern'.",
            },
            description: {
              type: "string" as const,
              description:
                "Concrete standard for this criterion, graded against the conversation. State what counts as 'full' and what triggers 'half' or 'not'.",
            },
          },
          required: ["label", "description"] as const,
        },
      },
    },
    required: ["criteria"] as const,
  };
}

/**
 * The raw shape a bot tool-call's `advanceRubric` input arrives in.
 * Always normalize via `parseAdvanceRubricArg` before passing
 * downstream.
 */
export interface RawBotAdvanceRubric {
  criteria?: Array<{ label: string; description?: string }>;
}

/**
 * Convert a bot tool-call's advanceRubric input into the shape
 * `activities.upsertInternal` expects (`{ criteria: [...] }`). Returns
 * undefined when the caller didn't pass one, or passed an empty
 * criteria array (an empty advance rubric is meaningless — treat it as
 * absent so the online-grading guard still fires).
 */
export function parseAdvanceRubricArg(
  raw: RawBotAdvanceRubric | undefined,
): { criteria: DeliverableCriterion[] } | undefined {
  if (!raw) return undefined;
  const criteria = (raw.criteria ?? [])
    .filter((c) => c.label?.trim())
    .map((c) => ({
      // Blank id triggers the normalizer's slug-from-label path.
      id: "",
      label: c.label,
      description: c.description,
    }));
  if (criteria.length === 0) return undefined;
  return { criteria };
}

/**
 * The bot expects a specific error-recovery message when
 * upsertInternal throws REFUSED — it tells the model how to re-call
 * with a valid evaluation shape. Centralized here so all three streams
 * surface the same instruction.
 */
export function refusedRecoveryMessage(
  toolName: string,
  matchHint: string,
): {
  error: string;
  actionRequired: string;
} {
  return {
    error: "REFUSED",
    actionRequired:
      `Re-call ${toolName} with the same ${matchHint} and ATTACH exactly ONE evaluation shape. ` +
      `If the scholar produces a DOCUMENT/product, pass a deliverable: ` +
      `{ kind, prompt, mode: 'manual' | 'auto', criteria: [{label, description}, ...] } ` +
      `(manual: 3-6 dimensional criteria; auto: criteria: [] plus a notes string). ` +
      `This is a private quality map, not a completion gate; each full criterion becomes flair with its label and description shown together. ` +
      `If instead the learning happens IN CONVERSATION with no document — a discussion or a ` +
      `map/geography discovery quiz — pass an advanceRubric: { criteria: [{label, description}, ...] } ` +
      `and NO deliverable; the tutor grades the talk + map interactions and a full pass completes it.`,
  };
}
