/**
 * A library of example specs — the "juice" of the primitive. One schema, one
 * renderer, one self-check contract, spanning a wide slice of the K–8 map:
 * fractions & equivalence, number sense, multiplication/factors/distribution,
 * algebraic equality & solving-for-x, area vs. perimeter, and a calculus
 * foreshadow through speed-time area. Each is authored as plain data — exactly
 * what a tutor or curriculum author would emit.
 */
import type { ManipulativeSpec, MultiStepSequenceSpec } from "@/lib/manipulative/types";

export interface Playlist {
  id: string;
  title: string;
  gradeBand: string;
  blurb: string;
  items: ManipulativeSpec[];
  extraCredit?: ManipulativeSpec;
}

export const PLAYLISTS: Playlist[] = [
  {
    id: "fractions-equivalence",
    title: "Fractions & equivalence",
    gradeBand: "Grades 3–5",
    blurb: "The same wedges, cut and shaded by hand. A “half” lights up whether you make 1/2, 2/4, or 3/6.",
    items: [
      {
        kind: "partition",
        id: "make-half",
        concept: "Equivalent fractions",
        prompt: "Make one half.",
        discs: [{ parts: 4, shaded: 1 }],
        adjustable: ["parts", "shaded"],
        partsRange: [2, 12],
        goal: { type: "shadedFractionEquals", disc: 0, value: 0.5 },
      },
      {
        kind: "partition",
        id: "match-two",
        concept: "Equivalent fractions",
        prompt: "Shade both so they’re the same amount.",
        discs: [{ parts: 2, shaded: 1 }, { parts: 6, shaded: 1 }],
        adjustable: ["parts", "shaded"],
        partsRange: [2, 12],
        goal: { type: "discsEqualShadedArea" },
      },
      {
        kind: "partition",
        id: "thirds-explore",
        concept: "Unit fractions",
        prompt: "Cut the cake into more and more pieces. What happens to each piece?",
        discs: [{ parts: 3, shaded: 1 }],
        adjustable: ["parts", "shaded"],
        partsRange: [1, 12],
      },
    ],
    extraCredit: {
      kind: "partition",
      id: "piece-of-cake-three-fourths",
      concept: "Fraction puzzles",
      prompt: "Piece of Cake: make exactly three-fourths of the cake.",
      discs: [{ parts: 8, shaded: 2 }],
      adjustable: ["parts", "shaded"],
      partsRange: [2, 12],
      goal: { type: "shadedFractionEquals", disc: 0, value: 0.75 },
      extraCredit: true,
      source: "Math Circles Collaborative — Piece of Cake (mathcircles.org/activities)",
    },
  },
  {
    id: "number-line-sense",
    title: "Number sense on a line",
    gradeBand: "Grades 3–6",
    blurb: "Drag one knob. The position is the only feedback — the answer is never printed.",
    items: [
      {
        kind: "numberline",
        id: "place-7",
        concept: "Whole numbers",
        prompt: "Put the knob on 7.",
        min: 0,
        max: 10,
        tickStep: 1,
        snap: 1,
        start: 3,
        goal: { type: "placeAt", value: 7 },
      },
      {
        kind: "numberline",
        id: "place-three-quarters",
        concept: "Fractions on a line",
        prompt: "Place three-quarters.",
        min: 0,
        max: 1,
        tickStep: 0.25,
        start: 0.1,
        goal: { type: "placeFraction", num: 3, den: 4 },
      },
      {
        kind: "numberline",
        id: "research-station-hike",
        concept: "Positive and negative elevation",
        prompt: "Guide the hiker to the research station at +5 above sea level.",
        min: -2,
        max: 8,
        tickStep: 1,
        snap: 1,
        start: 1,
        orientation: "vertical",
        handleLabel: "Hiker",
        scene: { type: "mountain" },
        markers: [{ value: 0, label: "Sea level" }],
        goal: { type: "placeAt", value: 5 },
      },
      {
        kind: "numberline",
        id: "elevator-basement-floor",
        concept: "Negative numbers",
        prompt: "Take the elevator to basement floor −3.",
        min: -4,
        max: 5,
        tickStep: 1,
        snap: 1,
        start: 2,
        orientation: "vertical",
        handleLabel: "Elevator",
        scene: { type: "building" },
        markers: [{ value: 0, label: "Ground floor" }],
        goal: { type: "placeAt", value: -3 },
      },
      {
        kind: "numberline",
        id: "explore-line",
        concept: "Number line",
        prompt: "Slide the knob. Where do the halves land?",
        min: 0,
        max: 5,
        tickStep: 1,
        start: 2,
      },
    ],
    extraCredit: {
      kind: "numberline",
      id: "tiny-target-five-eighths",
      concept: "Fraction estimation",
      prompt: "Tiny target: place five-eighths without snap.",
      min: 0,
      max: 1,
      tickStep: 0.125,
      start: 0.2,
      goal: { type: "placeFraction", num: 5, den: 8, tolerance: 0.02 },
      extraCredit: true,
      source: "Math Circles Collaborative — fraction number-line challenges (mathcircles.org/activities)",
    },
  },
  {
    id: "multiplication-area-distribution",
    title: "Multiplication as area",
    gradeBand: "Grades 3–7",
    blurb: "Drag corners and split rectangles. Factors, commutativity, and the distributive property become visible area.",
    items: [
      {
        kind: "array",
        id: "make-12",
        concept: "Factors & commutativity",
        prompt: "Build a rectangle of exactly 12 tiles.",
        rows: 2,
        cols: 2,
        maxRows: 8,
        maxCols: 8,
        goal: { type: "productEquals", value: 12 },
      },
      {
        kind: "array",
        id: "make-24",
        concept: "Factors",
        prompt: "Now make 24. How many different ways can you?",
        rows: 3,
        cols: 3,
        maxRows: 8,
        maxCols: 8,
        goal: { type: "productEquals", value: 24 },
      },
      {
        kind: "array",
        id: "array-explore",
        concept: "Arrays",
        prompt: "Grow and shrink the array. What stays true when you turn it sideways?",
        rows: 3,
        cols: 4,
        maxRows: 8,
        maxCols: 8,
      },
      {
        // Charm layer: same productEquals goal/mechanics as "make-12" above —
        // arraySolved() still just checks rows * cols. The apples are a pure
        // visual stand-in for the neutral tile fill — `theme.fill.label` is
        // generative (any noun), resolved + cached by convex/manipulativeThemeIcons.

        kind: "array",
        id: "apple-crate-charm",
        concept: "Multiplication as area",
        prompt: "How many apples fill the crate? Build a rectangle of exactly 12.",
        rows: 2,
        cols: 2,
        maxRows: 8,
        maxCols: 8,
        goal: { type: "productEquals", value: 12 },
        theme: { fill: { label: "apple" } },
      },
      {
        kind: "distribute",
        id: "distributor-explore",
        concept: "Distributive property",
        prompt: "Slide the cut. How does 8 × 7 split into two easier products?",
        width: 8,
        height: 7,
        startColumn: 3,
        source: "Distributor (equal sharing)",
      },
      {
        kind: "distribute",
        id: "split-8-by-7-at-5",
        concept: "Distributive property",
        prompt: "Split the 8 × 7 so the left piece is 5 wide.",
        width: 8,
        height: 7,
        startColumn: 2,
        goal: { type: "splitAt", column: 5 },
        source: "Distributor (equal sharing)",
      },
      {
        kind: "distribute",
        id: "friendly-ten-split",
        concept: "Friendly tens",
        prompt: "Split 12 × 4 into a friendly ten and what’s left.",
        width: 12,
        height: 4,
        startColumn: 6,
        goal: { type: "splitAt", column: 10 },
        source: "Distributor (equal sharing)",
      },
    ],
    extraCredit: {
      kind: "array",
      id: "factor-game-36",
      concept: "Factor Game",
      prompt: "Factor Game: build 36, then figure out how many rectangle shapes it can make.",
      rows: 5,
      cols: 6,
      maxRows: 12,
      maxCols: 12,
      goal: { type: "productEquals", value: 36 },
      answer: { value: 5, prompt: "How many different rectangle shapes make 36?" },
      extraCredit: true,
      source: "Math Circles Collaborative — Factor Game (mathcircles.org/activities)",
    },
  },
  {
    id: "number-bonds-sharing",
    title: "Number bonds & sharing",
    gradeBand: "Grades K–4",
    blurb:
      "A bead rack and a sharing machine. Push a group of beads across the rods to feel a number bond; deal a pile onto equal plates to feel division — remainder and all.",
    items: [
      {
        kind: "rekenrek",
        id: "rack-explore-8",
        concept: "Number bonds",
        prompt: "Push the beads. What two numbers hide inside 8?",
        total: 8,
        startLeft: 0,
      },
      {
        kind: "rekenrek",
        id: "rack-9-group-of-6",
        concept: "Decomposing a number",
        prompt: "Push the 9 beads so one group holds exactly 6.",
        total: 9,
        startLeft: 0,
        goal: { type: "groupOf", value: 6 },
      },
      {
        kind: "rekenrek",
        id: "rack-make-ten-13",
        concept: "Make-ten strategy",
        prompt: "Make ten: push 13 into a group of 10 and the leftover ones.",
        total: 13,
        startLeft: 0,
        goal: { type: "groupOf", value: 10 },
      },
      {
        kind: "distributor",
        id: "share-explore-12-by-3",
        concept: "Equal sharing",
        prompt: "Deal these 12 fairly onto 3 plates. How many land on each?",
        total: 12,
        groups: 3,
      },
      {
        kind: "distributor",
        id: "share-12-by-4",
        concept: "Division as sharing",
        prompt: "Share all 12 cookies equally onto the 4 plates.",
        total: 12,
        groups: 4,
        goal: { type: "shareEqually" },
        source: "Distributor (equal sharing)",
      },
      {
        kind: "distributor",
        id: "share-13-by-4-remainder",
        concept: "Remainders",
        prompt: "Share 13 onto 4 plates. Deal every full round you can — what's left over?",
        total: 13,
        groups: 4,
        goal: { type: "shareEqually" },
        source: "Distributor (equal sharing)",
      },
    ],
    extraCredit: {
      kind: "distributor",
      id: "share-23-by-5-remainder",
      concept: "Remainders",
      prompt: "Tricky share: deal 23 onto 5 plates. How many each, and how many left over?",
      total: 23,
      groups: 5,
      goal: { type: "shareEqually" },
      extraCredit: true,
      source: "Distributor (equal sharing)",
    },
  },
  {
    id: "equality-unknowns",
    title: "Equality & solving for x",
    gradeBand: "Grades 4–7",
    blurb: "A pan balance. Level means equal. A mystery box turns it into algebra — no equation in sight.",
    items: [
      {
        kind: "balance",
        id: "balance-basic",
        concept: "Equality",
        prompt: "Make the scale balance.",
        left: 5,
        right: 2,
        adjustable: ["left", "right"],
        maxUnits: 12,
        goal: { type: "balance" },
      },
      {
        kind: "balance",
        id: "solve-x",
        concept: "Solving for an unknown",
        prompt: "Add blocks to the left until it balances. Then type what’s in the box.",
        left: 0,
        right: 2,
        mysteryRight: 3,
        adjustable: ["left"],
        maxUnits: 12,
        answer: { value: 3, prompt: "What’s in the box?" },
      },
    ],
    extraCredit: {
      kind: "balance",
      id: "bubbling-cauldron",
      concept: "Hidden-number balance",
      prompt: "Bubbling Cauldrons: level the pan, then infer the hidden cauldron number.",
      left: 0,
      right: 4,
      mysteryRight: 5,
      adjustable: ["left"],
      maxUnits: 14,
      answer: { value: 5, prompt: "What number is hiding in the cauldron?" },
      extraCredit: true,
      source: "Math Circles Collaborative — Bubbling Cauldrons (mathcircles.org/activities)",
      theme: { fill: { label: "cauldron" } },
    },
  },
  {
    id: "function-machines",
    title: "Function machines",
    gradeBand: "Grades 4–7",
    blurb:
      "A hidden rule turns every input into an output. Study the worked examples, guess the rule, then predict — no answer ever printed until you commit.",
    items: [
      {
        kind: "functionMachine",
        id: "machine-times-two",
        concept: "Functions & patterns",
        prompt: "Figure out the machine's rule, then predict what comes out.",
        rule: { op: "affine", m: 2, b: 0 },
        examples: [
          { in: 1, out: 2 },
          { in: 3, out: 6 },
          { in: 5, out: 10 },
        ],
        queryInput: 7,
        answer: { value: 14, prompt: "What comes out when 7 goes in?" },
      },
      {
        kind: "functionMachine",
        id: "machine-plus-three",
        concept: "Functions & patterns",
        prompt: "Figure out the machine's rule, then predict what comes out.",
        rule: { op: "affine", m: 1, b: 3 },
        examples: [
          { in: 2, out: 5 },
          { in: 4, out: 7 },
          { in: 10, out: 13 },
        ],
        queryInput: 20,
        answer: { value: 23, prompt: "What comes out when 20 goes in?" },
      },
      {
        kind: "functionMachine",
        id: "machine-double-plus-one",
        concept: "Functions & patterns",
        prompt: "Two steps hide in this one — double the input, then bump it by one.",
        rule: { op: "affine", m: 2, b: 1 },
        examples: [
          { in: 1, out: 3 },
          { in: 2, out: 5 },
          { in: 4, out: 9 },
        ],
        queryInput: 6,
        answer: { value: 13, prompt: "What comes out when 6 goes in?" },
      },
    ],
    extraCredit: {
      kind: "functionMachine",
      id: "machine-hard-triple-minus-two",
      concept: "Functions & patterns",
      prompt: "A trickier machine: negative numbers count too.",
      rule: { op: "affine", m: 3, b: -2 },
      examples: [
        { in: 0, out: -2 },
        { in: 2, out: 4 },
        { in: 5, out: 13 },
      ],
      queryInput: 12,
      answer: { value: 34, prompt: "What comes out when 12 goes in?" },
      extraCredit: true,
      source: "Catalog shape 3a — Function Machines (review/manipulative-catalog.html)",
    },
  },
  {
    id: "area-perimeter-motion",
    title: "Area, perimeter & motion",
    gradeBand: "Grades 5–8",
    blurb: "Same fence, different room — then a speed-time graph where distance is the area you can count.",
    items: [
      {
        kind: "areaPerimeter",
        id: "biggest-pen",
        concept: "Area vs. perimeter",
        prompt: "Same fence. Make the pen hold the most room.",
        perimeter: 24,
        startWidth: 2,
        goal: { type: "maxArea" },
      },
      {
        kind: "areaPerimeter",
        id: "area-explore",
        concept: "Area vs. perimeter",
        prompt: "Keep the fence the same length. Watch the squares inside change.",
        perimeter: 20,
        startWidth: 3,
      },
      {
        // Charm layer: same maxArea goal/mechanics as "biggest-pen" above —
        // areaPerimeterSolved()/areaPerimeterArea() still do the counting.
        // The pig is a pure visual stand-in for the neutral cell fill.
        kind: "areaPerimeter",
        id: "pig-fence-charm",
        concept: "Area vs. perimeter",
        prompt: "How many pigs can you fence in?",
        perimeter: 24,
        startWidth: 2,
        goal: { type: "maxArea" },
        theme: { fill: { label: "pig" } },
      },
      {
        kind: "riemann",
        id: "speed-distance-explore",
        concept: "Speed → distance",
        prompt: "Add more bars. What happens to the leftover gaps under the speed line?",
        slope: 0.5,
        intercept: 1,
        tMax: 8,
        startBars: 3,
        maxBars: 20,
      },
      {
        kind: "riemann",
        id: "distance-within-one-square",
        concept: "Area under a graph",
        prompt: "Estimate the distance to within one square by adding bars.",
        slope: 0.5,
        intercept: 1,
        tMax: 8,
        startBars: 4,
        maxBars: 20,
        goal: { type: "approximateWithin", tolerance: 1 },
      },
    ],
    extraCredit: {
      kind: "areaPerimeter",
      id: "lattice-pen-48",
      concept: "Lattice area",
      prompt: "Pick’s Theorem warm-up: with 28 fence units, make a rectangle of area 48.",
      perimeter: 28,
      startWidth: 3,
      goal: { type: "areaEquals", value: 48 },
      extraCredit: true,
      source: "Math Circles Collaborative — Pick’s Theorem / lattice area (mathcircles.org/activities)",
    },
  },
  {
    id: "probability-lab",
    title: "Probability",
    gradeBand: "Grades 5–7",
    blurb: "Enrichment: roll and tally evidence, then commit the theoretical prediction the tray never reveals.",
    items: [
      {
        kind: "dice",
        id: "probability-even-d6",
        concept: "Probability",
        prompt: "What is the probability that one d6 lands on an even number?",
        diceType: "d6",
        themeColor: "#2ECCDF",
        prediction: { type: "probability", event: { type: "even" } },
      },
      {
        kind: "dice",
        id: "probability-heads-coin",
        concept: "Probability",
        prompt: "What is the probability that one coin lands heads?",
        diceType: "coin",
        themeColor: "#FFA639",
        prediction: { type: "probability", event: { type: "face", value: 1 } },
      },
      {
        kind: "dice",
        id: "probability-d6-faces-greater-than-four",
        concept: "Favorable outcomes",
        prompt: "How many faces on a d6 are greater than 4?",
        diceType: "d6",
        themeColor: "#00DD91",
        prediction: { type: "favorableCount", event: { type: "greaterThan", value: 4 } },
      },
      {
        kind: "dice",
        id: "probability-two-dice-likely-total",
        concept: "Likely totals",
        prompt: "Roll two dice. Which total is most likely?",
        diceType: "d6",
        count: 2,
        themeColor: "#a960bc",
        prediction: { type: "mostLikelyTotal" },
      },
    ],
  },
  {
    id: "angles-with-a-protractor",
    title: "Angles with a protractor",
    gradeBand: "Grades 4–6",
    blurb: "Drag the free ray until it reads the stated angle on the scale — two constructions, two different starting rotations.",
    items: [
      {
        kind: "protractor",
        id: "construct-65-degrees",
        concept: "Constructing angles",
        prompt: "Construct a 65° angle — drag the free ray until it reads 65° on the scale.",
        startDeg: 10,
        goal: { type: "constructAngle", targetDeg: 65 },
      },
      {
        kind: "protractor",
        id: "construct-130-degrees-rotated",
        concept: "Constructing angles",
        prompt: "Construct a 130° angle — drag the free ray until it reads 130° on the scale.",
        baseRayDeg: 40,
        startDeg: 20,
        goal: { type: "constructAngle", targetDeg: 130 },
      },
    ],
  },
  {
    id: "coordinate-plane-geometry",
    title: "The coordinate plane",
    gradeBand: "Grades 5–8",
    blurb: "Drag the point(s) onto the grid. One example per goal shape — plotting, reflecting, and completing a rectangle.",
    items: [
      {
        kind: "coordinatePlane",
        id: "plot-point-first-quadrant",
        concept: "Plotting a point",
        prompt: "Plot the point (4, 2).",
        xMin: 0,
        xMax: 8,
        yMin: 0,
        yMax: 8,
        gridStep: 1,
        draggable: [{ start: { x: 1, y: 6 } }],
        goal: { type: "placePoint", x: 4, y: 2 },
      },
      {
        kind: "coordinatePlane",
        id: "plot-two-points-four-quadrant",
        concept: "Plotting in all four quadrants",
        prompt: "Plot both (−3, 2) and (3, −2) — any order.",
        xMin: -5,
        xMax: 5,
        yMin: -5,
        yMax: 5,
        gridStep: 1,
        draggable: [{ start: { x: 0, y: 0 } }, { start: { x: 4, y: 4 } }],
        goal: { type: "placePoints", points: [{ x: -3, y: 2 }, { x: 3, y: -2 }] },
      },
      {
        kind: "coordinatePlane",
        id: "complete-the-rectangle",
        concept: "Coordinates & shape",
        prompt: "Three corners of a rectangle are marked. Drag the point to the missing fourth corner.",
        xMin: 0,
        xMax: 8,
        yMin: 0,
        yMax: 6,
        gridStep: 1,
        fixedPoints: [
          { x: 1, y: 1, label: "A" },
          { x: 6, y: 1, label: "B" },
          { x: 1, y: 4, label: "C" },
        ],
        segments: [
          [{ x: 1, y: 1 }, { x: 6, y: 1 }],
          [{ x: 1, y: 1 }, { x: 1, y: 4 }],
        ],
        draggable: [{ start: { x: 4, y: 5 } }],
        goal: { type: "completeRectangle" },
      },
      {
        kind: "coordinatePlane",
        id: "reflect-across-x-axis",
        concept: "Reflections",
        prompt: "Reflect point P across the x-axis.",
        xMin: -6,
        xMax: 6,
        yMin: -6,
        yMax: 6,
        gridStep: 1,
        fixedPoints: [{ x: -4, y: 3, label: "P" }],
        draggable: [{ start: { x: 2, y: 2 } }],
        goal: { type: "reflectPoint", point: { x: -4, y: 3 }, across: "x" },
      },
      {
        kind: "coordinatePlane",
        id: "explore-plane",
        concept: "The coordinate plane",
        prompt: "Drag the point around. What changes as you cross an axis?",
        xMin: -5,
        xMax: 5,
        yMin: -5,
        yMax: 5,
        gridStep: 1,
        draggable: [{ start: { x: 2, y: 2 } }],
      },
    ],
    extraCredit: {
      kind: "coordinatePlane",
      id: "reflect-across-y-tight-grid",
      concept: "Reflections",
      prompt: "Extra credit: reflect point Q across the y-axis on a half-step grid.",
      xMin: -4,
      xMax: 4,
      yMin: -4,
      yMax: 4,
      gridStep: 0.5,
      fixedPoints: [{ x: -2.5, y: 1.5, label: "Q" }],
      draggable: [{ start: { x: 1, y: -1 } }],
      goal: { type: "reflectPoint", point: { x: -2.5, y: 1.5 }, across: "y" },
      extraCredit: true,
    },
  },
  {
    id: "measure-length-capacity",
    title: "Measuring length & capacity",
    gradeBand: "Grades 2–4",
    blurb:
      "Build a length against a ruler that doesn't start at zero, then pour to the mark. Both ask the same question: how much, read off a scale.",
    items: [
      {
        kind: "ruler",
        id: "ruler-explore-cm",
        concept: "Measuring length",
        prompt: "Drag the end of the bar. Watch how its length changes.",
        unit: "cm",
        length: 12,
        startEnd: 4,
      },
      {
        // Pinned at 2, not 0. A zero-start graded ruler is `numberline`
        // `placeAt` wearing a ruler skin — the end position and the length are
        // the same number, so nothing new is being asked. Every GRADED ruler
        // item therefore starts off zero; the free explorer above keeps
        // `startAt: 0` because orienting to the tool is its whole job.
        kind: "ruler",
        id: "ruler-make-7cm",
        concept: "Measuring length",
        prompt: "The bar starts at 2. Make it exactly 7 cm long.",
        unit: "cm",
        length: 12,
        startAt: 2,
        startEnd: 4,
        goal: { type: "lengthEquals", value: 7 },
        source: "Ruler (linear measurement)",
      },
      {
        // The broken ruler: the bar is pinned at 3, so the number its end lands
        // on (8) is NOT its length (5). The whole reason this kind exists.
        kind: "ruler",
        id: "ruler-broken-start-3-make-5cm",
        concept: "Length is end minus start",
        prompt: "The bar starts at 3, not 0. Make it 5 cm long anyway.",
        unit: "cm",
        length: 12,
        startAt: 3,
        startEnd: 4,
        goal: { type: "lengthEquals", value: 5 },
        source: "Ruler (broken-ruler measurement)",
      },
      {
        kind: "ruler",
        id: "ruler-quarter-inch-2-and-three-quarters",
        concept: "Halves & quarters of an inch",
        prompt: "The bar starts at 1¼. Make it 2¾ inches long — count the quarter marks.",
        unit: "in",
        length: 6,
        precision: 0.25,
        startAt: 1.25,
        startEnd: 2,
        goal: { type: "lengthEquals", value: 2.75 },
        source: "Ruler (quarter-inch scale)",
      },
      {
        kind: "liquid",
        id: "liquid-explore-jars",
        concept: "Capacity",
        prompt: "Pour the jars up and down. Which one holds more?",
        unit: "cup",
        vessels: [
          { capacity: 4, label: "Tall jar" },
          { capacity: 2, label: "Short jar" },
        ],
      },
      {
        kind: "liquid",
        id: "liquid-fill-3-cups",
        concept: "Liquid volume",
        prompt: "Pour the tall jar until it holds exactly 3 cups.",
        unit: "cup",
        vessels: [{ capacity: 4, label: "Tall jar" }],
        goal: { type: "fillTo", vessel: 0, value: 3 },
        source: "Measuring jars (liquid volume)",
      },
      {
        // totalEquals with a 5-cup target over 4- and 2-cup jars: no single jar
        // can hold it, so the amount genuinely has to be shared out.
        kind: "liquid",
        id: "liquid-total-5-cups",
        concept: "Composing measures",
        prompt: "Get 5 cups altogether — no single jar is big enough.",
        unit: "cup",
        vessels: [
          { capacity: 4, label: "Tall jar" },
          { capacity: 2, label: "Short jar" },
        ],
        goal: { type: "totalEquals", value: 5 },
        source: "Measuring jars (composing measures)",
      },
    ],
    extraCredit: {
      kind: "liquid",
      id: "liquid-half-cups-total-3-and-a-half",
      concept: "Halves of a cup",
      prompt: "Extra credit: 3½ cups altogether, using half-cup marks.",
      unit: "cup",
      vessels: [
        { capacity: 2, label: "Left jar" },
        { capacity: 2, label: "Right jar" },
      ],
      step: 0.5,
      goal: { type: "totalEquals", value: 3.5 },
      extraCredit: true,
    },
  },
  {
    id: "time-and-money",
    title: "Telling time & counting money",
    gradeBand: "Grades 1–3",
    blurb:
      "A geared clock whose hour hand creeps as the minutes pass, and a tray of real US coins where the dime is smaller than the nickel.",
    items: [
      {
        kind: "clock",
        id: "clock-explore",
        concept: "Telling time",
        prompt: "Drag the minute hand all the way round. Watch the hour hand.",
        startHour: 3,
        startMinute: 0,
        snapMinutes: 5,
        showMinuteNumerals: true,
      },
      {
        kind: "clock",
        id: "clock-show-half-past-4",
        concept: "Half past",
        prompt: "Make the clock show half past 4.",
        startHour: 12,
        startMinute: 0,
        snapMinutes: 30,
        goal: { type: "showTime", hour: 4, minute: 30 },
        source: "Clock (hour & half hour)",
      },
      {
        kind: "clock",
        id: "clock-show-3-45",
        concept: "Time to five minutes",
        prompt: "Make the clock show 3:45. Look where the hour hand ends up.",
        startHour: 9,
        startMinute: 0,
        snapMinutes: 5,
        showMinuteNumerals: true,
        goal: { type: "showTime", hour: 3, minute: 45 },
        source: "Clock (five-minute intervals)",
      },
      {
        kind: "clock",
        id: "clock-elapsed-20-past-2-50",
        concept: "Elapsed time",
        prompt: "It's 2:50. Move the hands on by 20 minutes.",
        startHour: 2,
        startMinute: 50,
        snapMinutes: 5,
        goal: { type: "advanceBy", minutes: 20 },
        source: "Clock (elapsed time across the hour)",
      },
      {
        kind: "money",
        id: "money-explore-coins",
        concept: "US coins",
        prompt: "Add coins to the tray. Which one is worth most for its size?",
        available: ["penny", "nickel", "dime", "quarter"],
      },
      {
        kind: "money",
        id: "money-make-47-cents",
        concept: "Counting money",
        prompt: "Put exactly 47¢ in the tray.",
        available: ["penny", "nickel", "dime", "quarter"],
        goal: { type: "amountEquals", cents: 47 },
        source: "Money (counting a coin collection)",
      },
      {
        kind: "money",
        id: "money-30-cents-in-4-coins",
        concept: "Coin combinations",
        prompt: "Make 30¢ using exactly 4 coins.",
        available: ["penny", "nickel", "dime", "quarter"],
        goal: { type: "amountEqualsWithCount", cents: 30, count: 4 },
        source: "Money (a constrained decomposition)",
      },
      {
        kind: "money",
        id: "money-fewest-coins-63-cents",
        concept: "Fewest coins",
        prompt: "Make 63¢ with as few coins as you can.",
        available: ["penny", "nickel", "dime", "quarter"],
        goal: { type: "fewestPieces", cents: 63 },
        source: "Money (minimising the count)",
      },
    ],
    extraCredit: {
      kind: "money",
      id: "money-fewest-pieces-1-dollar-85",
      concept: "Dollars & cents",
      prompt: "Extra credit: make $1.85 with as few pieces as you can — bills count.",
      available: ["penny", "nickel", "dime", "quarter", "halfDollar", "oneDollarBill"],
      goal: { type: "fewestPieces", cents: 185 },
      extraCredit: true,
    },
  },
];

/**
 * The two-player Factor Game used to live here as the spike's Model-B example
 * (`FACTOR_GAME_SPEC`). It is a GAME now — `native/src/games/factor-game/` —
 * and no longer a `ManipulativeKind`, because grading a child on whether they
 * out-scored a greedy bot was never evidence of understanding factors.
 *
 * Unaffected and still above: the unrelated "Factor Game"-named array challenge
 * (`factor-game-36`, in Multiplication as area), which is a build-a-rectangle
 * puzzle and a perfectly ordinary manipulative.
 */

/**
 * The spike's Model-A example, now expressed as DATA (a `MultiStepSequenceSpec`
 * — see `types.ts`) instead of hardcoded JSX: a mini-playlist of two ordinary,
 * independently-graded steps (`numberline` then `partition`, unmodified) with
 * NO state carried between them. Rendered by the one generic
 * `MultiStepSequenceChallenge` — see `components/manipulative/challenges/`.
 */
export const TWO_STEP_DEMO_SEQUENCE: MultiStepSequenceSpec = {
  id: "two-step-demo",
  concept: "A linked sequence (Model A)",
  title: "Two-step warm-up",
  completeSummary: "Both steps solved — this is the same frame the Factor Game uses above.",
  steps: [
    {
      kind: "numberline",
      id: "twostep-demo-numberline",
      concept: "Number sense",
      prompt: "Step 1 — put the knob on 5.",
      min: 0,
      max: 10,
      tickStep: 1,
      snap: 1,
      start: 1,
      goal: { type: "placeAt", value: 5 },
    },
    {
      kind: "partition",
      id: "twostep-demo-partition",
      concept: "Equivalent fractions",
      prompt: "Step 2 — now make one half.",
      discs: [{ parts: 4, shaded: 1 }],
      adjustable: ["parts", "shaded"],
      partsRange: [2, 12],
      goal: { type: "shadedFractionEquals", disc: 0, value: 0.5 },
    },
  ],
};

export const LIBRARY = PLAYLISTS;

export const ALL_SPECS: ManipulativeSpec[] = PLAYLISTS.flatMap((playlist) => [
  ...playlist.items,
  ...(playlist.extraCredit ? [playlist.extraCredit] : []),
]);
